
<h3 class="titulo">Modulo de Salud </h3>
<hr>
<div class="row-fluid">
    <div class="span6">
        <h1>BIENVENIDO AL MÓDULO</h1><h1> DE SALUD </h1>
    </div>
    <div class="span6">
        <img src="/images/noticias/salud.jpg" alt="" style="width: 500px"/>
    </div>
</div>
<div class="row-fluid">
    <div class="span4">
        <h4 class="titulo">Bogotá más de 20 mil millones para ampliar cupos en universidades públicas </h4>
        <p>

            Con esta inversión, Bogotá es la primera ciudad del país que aporta de manera contundente a la ampliación y creación de nuevos cupos en 3 instituciones públicas de educación superior.
            La iniciativa permite que más de mil estudiantes egresados de colegios distritales tengan acceso a una educación superior de calidad. La convocatoria para aplicar a los nuevos cupos estará abierta del 9 al 29 de julio
        </p>
    </div>
    <div class="span4">
        <h4 class="titulo">
            <p>Implementación de estudios superiores en la localidad de Ciudad Bolívar</h4>
        En la actualidad la Secretaria de Educación del Distrito SED se encuentra adelantando el proyecto de educación  media fortalecida  y mayor acceso ala educación  superior, en el marco del cual se desarrollaran las siguientes estrategias.</p>
    </div>
    <div class="span4">
        <h4 class="titulo">Proyecto 1129 “Ciudad Bolívar Construye Saberes” Vigencia 2014</h4>
        <p>Meta PDL: “Vincular 500 personas como mínimo con programas de preparación y capacitación para primaria o bachillerato dirigido a jóvenes y adultos en edad extraescolar.”

            En el período 2007-2011 la tasa de analfabetismo en Bogotá disminuyó de 1,8% a 1,6%, alcanzando el 1,3% en hombres de 15 y más años, y el 1,9% en mujeres. Esta tasa significa que en Bogotá cerca de 91.793 personas de 15 y más años, no saben leer ni escribir, de los cuales 34.119 son  hombres y 57.674 son mujeres.</p>
    </div>
</div>