<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta()
                ->setCharset('UTF-8')
                ->appendHttpEquiv('Content-Language', 'es_ES')
                ->appendName('keywords', 'ciudad, bolivar, observatorio, alcaldia, localidad');
        //->appendHttpEquiv('Refresh','3;URL=http://www.facebook.com/');sirve para direccionar en x cantidad de tiempo :O
        ?>
        <?php echo $this->HeadTitle($this->titulo); ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                ->prependStylesheet($this->basePath() . "/css/bootstrap-responsive.css")
                ->prependStylesheet($this->basePath() . "/css/bootstrap.css")
                ->prependStylesheet($this->basePath() . "/css/prettyPhoto.css");
        ?>     
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.js')
                ->prependFile($this->basePath() . '/js/jquery-validate.js')
                ->prependFile($this->basePath() . '/js/jquery.prettyPhoto.js')
                ->prependFile($this->basePath() . "/js/jquery-1.11.1.js")
        ?>
    </head>
    <body style="background-image: url('/img/keys.png')">
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <?php if ($this->identity()) { ?>
                        <div class="span7">
                            <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                        </div>
                        <div class="span4 text-right">
                            <?php echo '</br>Bienvenid@ ' . $this->identity()->usuario_nombre . ' ' . $this->identity()->usuario_apellido . '&nbsp; <button id="changue" title="Cambio de Contraseña" class="btn btn-mini"><i class="icon-cog"></i></button></br>'; ?>
                        </div>
                        <div class="span1"  style="margin-top: 15px;">
                            <?php echo "<a class='btn btn-warning' href=\"" . $this->basePath() . "/login/logout\">Salir</a>"; ?>
                        </div>
                    <?php } else { ?>
                        <div class="span10">
                            <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                        </div>
                        <div class="span2"  style="margin: 15px 2% 0px 0px;">
                            <a class="btn btn-info" href="<?php echo $this->basePath() ?>/login">Ingresar</a>
                        </div>
                    <?php } ?>
                </div>
            </div>

            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand">Observatorio Social</a>
                    <ul class="nav">
                        <li>
                            <a href="#" onclick="history.go(-1);"><span class="icon-home"></span>Volver</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="contenido">
            <div class="row-fluid">
                <div class="span4">
                    <img class="img-circle left" src="/img/STOP.png">
                </div>
                <div class="span8">
                    <label class="label label-important"><h1>Acceso Denegado</h1></label>
                    <h3>Lo sentimos no tiene acceso esta pagina, pongase en contacto con el administrador</h3>
                </div>
            </div>
        </div>
    </body>
</html>
