<?php

namespace DoctrineORMModule\Proxy\__CG__\Login\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proyecto extends \Login\Model\Entity\Proyecto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoId', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoPresupuesto', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoPathfotos', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoAnio', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoResultados', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'eje', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'estado');
        }

        return array('__isInitialized__', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoId', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoPresupuesto', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoPathfotos', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoAnio', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'proyectoResultados', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'eje', '' . "\0" . 'Login\\Model\\Entity\\Proyecto' . "\0" . 'estado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proyecto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProyectoId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProyectoId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectoId', array());

        return parent::getProyectoId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectoPresupuesto($proyectoPresupuesto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectoPresupuesto', array($proyectoPresupuesto));

        return parent::setProyectoPresupuesto($proyectoPresupuesto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectoPresupuesto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectoPresupuesto', array());

        return parent::getProyectoPresupuesto();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectoPathfotos($proyectoPathfotos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectoPathfotos', array($proyectoPathfotos));

        return parent::setProyectoPathfotos($proyectoPathfotos);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectoPathfotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectoPathfotos', array());

        return parent::getProyectoPathfotos();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectoAnio($proyectoAnio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectoAnio', array($proyectoAnio));

        return parent::setProyectoAnio($proyectoAnio);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectoAnio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectoAnio', array());

        return parent::getProyectoAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectoResultados($proyectoResultados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectoResultados', array($proyectoResultados));

        return parent::setProyectoResultados($proyectoResultados);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectoResultados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectoResultados', array());

        return parent::getProyectoResultados();
    }

    /**
     * {@inheritDoc}
     */
    public function setEje(\Login\Model\Entity\Eje $eje = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEje', array($eje));

        return parent::setEje($eje);
    }

    /**
     * {@inheritDoc}
     */
    public function getEje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEje', array());

        return parent::getEje();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\Login\Model\Entity\Estado $estado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

}
