<?php

namespace DoctrineORMModule\Proxy\__CG__\Login\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProyectoSalud extends \Login\Model\Entity\ProyectoSalud implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludId', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludObjetivo', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludFechainicio', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludPlazoejecucion', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludNumero', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludEjecutor', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludObjetocontractual', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludNombre', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyecto', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'segmento');
        }

        return array('__isInitialized__', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludId', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludObjetivo', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludFechainicio', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludPlazoejecucion', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludNumero', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludEjecutor', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludObjetocontractual', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyectosaludNombre', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'proyecto', '' . "\0" . 'Login\\Model\\Entity\\ProyectoSalud' . "\0" . 'segmento');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProyectoSalud $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProyectosaludId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProyectosaludId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludId', array());

        return parent::getProyectosaludId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectosaludObjetivo($proyectosaludObjetivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectosaludObjetivo', array($proyectosaludObjetivo));

        return parent::setProyectosaludObjetivo($proyectosaludObjetivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectosaludObjetivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludObjetivo', array());

        return parent::getProyectosaludObjetivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectosaludFechainicio($proyectosaludFechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectosaludFechainicio', array($proyectosaludFechainicio));

        return parent::setProyectosaludFechainicio($proyectosaludFechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectosaludFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludFechainicio', array());

        return parent::getProyectosaludFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectosaludPlazoejecucion($proyectosaludPlazoejecucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectosaludPlazoejecucion', array($proyectosaludPlazoejecucion));

        return parent::setProyectosaludPlazoejecucion($proyectosaludPlazoejecucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectosaludPlazoejecucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludPlazoejecucion', array());

        return parent::getProyectosaludPlazoejecucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectosaludNumero($proyectosaludNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectosaludNumero', array($proyectosaludNumero));

        return parent::setProyectosaludNumero($proyectosaludNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectosaludNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludNumero', array());

        return parent::getProyectosaludNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectosaludEjecutor($proyectosaludEjecutor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectosaludEjecutor', array($proyectosaludEjecutor));

        return parent::setProyectosaludEjecutor($proyectosaludEjecutor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectosaludEjecutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludEjecutor', array());

        return parent::getProyectosaludEjecutor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectosaludObjetocontractual($proyectosaludObjetocontractual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectosaludObjetocontractual', array($proyectosaludObjetocontractual));

        return parent::setProyectosaludObjetocontractual($proyectosaludObjetocontractual);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectosaludObjetocontractual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludObjetocontractual', array());

        return parent::getProyectosaludObjetocontractual();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyectosaludNombre($proyectosaludNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyectosaludNombre', array($proyectosaludNombre));

        return parent::setProyectosaludNombre($proyectosaludNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyectosaludNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyectosaludNombre', array());

        return parent::getProyectosaludNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyecto(\Login\Model\Entity\Proyecto $proyecto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyecto', array($proyecto));

        return parent::setProyecto($proyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyecto', array());

        return parent::getProyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function setSegmento(\Login\Model\Entity\Segmento $segmento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSegmento', array($segmento));

        return parent::setSegmento($segmento);
    }

    /**
     * {@inheritDoc}
     */
    public function getSegmento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSegmento', array());

        return parent::getSegmento();
    }

}
