<?php

namespace DoctrineORMModule\Proxy\__CG__\Login\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lugar extends \Login\Model\Entity\Lugar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarId', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarNombre', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarDireccion', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarCoordenadas', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarTelefono', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'barrio', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'tipolugar');
        }

        return array('__isInitialized__', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarId', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarNombre', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarDireccion', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarCoordenadas', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'lugarTelefono', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'barrio', '' . "\0" . 'Login\\Model\\Entity\\Lugar' . "\0" . 'tipolugar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lugar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLugarId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLugarId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarId', array());

        return parent::getLugarId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarNombre($lugarNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarNombre', array($lugarNombre));

        return parent::setLugarNombre($lugarNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarNombre', array());

        return parent::getLugarNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarDireccion($lugarDireccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarDireccion', array($lugarDireccion));

        return parent::setLugarDireccion($lugarDireccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarDireccion', array());

        return parent::getLugarDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarCoordenadas($lugarCoordenadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarCoordenadas', array($lugarCoordenadas));

        return parent::setLugarCoordenadas($lugarCoordenadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarCoordenadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarCoordenadas', array());

        return parent::getLugarCoordenadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarTelefono($lugarTelefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarTelefono', array($lugarTelefono));

        return parent::setLugarTelefono($lugarTelefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarTelefono', array());

        return parent::getLugarTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarrio(\Login\Model\Entity\Barrio $barrio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarrio', array($barrio));

        return parent::setBarrio($barrio);
    }

    /**
     * {@inheritDoc}
     */
    public function getBarrio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarrio', array());

        return parent::getBarrio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipolugar(\Login\Model\Entity\TipoLugar $tipolugar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipolugar', array($tipolugar));

        return parent::setTipolugar($tipolugar);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipolugar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipolugar', array());

        return parent::getTipolugar();
    }

}
