<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
            echo $this->headMeta()
                    ->setCharset('UTF-8')
                    ->appendHttpEquiv('Content-Language', 'es_ES')
                    ->appendName('keywords', 'ciudad, bolivar, observatorio, alcaldia, localidad');
            echo $this->HeadTitle($this->titulo);
            echo $this->headLink(array('rel' => 'shortcut icon',
                        'type' => 'image/vnd.microsoft.icon',
                        'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                    ->prependStylesheet($this->basePath() . "/css/bootstrap-responsive.css")
                    ->prependStylesheet($this->basePath() . "/css/bootstrap.css");

            echo $this->headScript()
                    ->prependFile($this->basePath() . "/js/bootstrap.js")
                    ->prependFile($this->basePath() . "/js/jquery.validationEngine-es.js")
                    ->prependFile($this->basePath() . "/js/jquery.validationEngine.js")
                    ->prependFile($this->basePath() . "/js/jquery-validate.js")
                    ->prependFile($this->basePath() . "/js/jquery.jtable.es.js")
                    ->prependFile($this->basePath() . "/js/jquery.jtable.min.js")
                    ->prependFile($this->basePath() . "/js/jquery.jtable.js")
                    ->prependFile($this->basePath() . "/js/jquery-ui.js")
                    ->prependFile($this->basePath() . "/js/jquery-1.9.1.js")
        ?>
        <script>
            jQuery().ready(function() {
                jQuery('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <div class="span10">
                        <img src="<?php echo $this->basePath(); ?>/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span2">
                        <?php
                            echo '</br>Bienvenido ' . $this->identity()->usuario_nombre . ' ' . $this->identity()->usuario_apellido . '</br>';
                            echo "<a class='btn btn-warning' href=\"" . $this->basePath() . "/login/logout\">Salir</a>";                            
                        ?>
                    </div>
                </div>
                
            </div>            
        </header>
        
        <div class="container-fluid">
            <div class="row-fluid">                
                <div class="span2">
                    <ul class="nav nav-tabs nav-stacked">
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/admin"><span class="icon-home"></span>&nbsp;Inicio</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a title="Crear nuevos usuarios" href="<?php echo $this->basePath(); ?>/admin/add">Crear</a></li>
                                <li><a title="Editar usuarios" href="<?php echo $this->basePath(); ?>/admin/consultarUsuario">Editar</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Perfiles<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a>Crear</a></li>
                                <li><a>Editar</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="span10" id="container">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <footer>
            <div class="footer">
                <p class="text-middle">
                    Nathaly Salamanca Rativa 20081078092 &amp;  Jeisson Barrero Molina 20082078008 &COPY; 2013 - <?php echo date('Y'); ?>
                </p>
            </div>
        </footer>
    </body>
</html>