<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta()
                ->setCharset('UTF-8')
                ->appendHttpEquiv('Content-Language', 'es_ES')
                ->appendName('keywords', 'ciudad, bolivar, observatorio, alcaldia, localidad');
        echo $this->HeadTitle($this->titulo);
        echo $this->headLink(array('rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                ->prependStylesheet($this->basePath() . "/css/jquery-ui.structure.min.css")
                ->prependStylesheet($this->basePath() . "/css/jquery-ui.structure.css")
                ->prependStylesheet($this->basePath() . "/css/jquery-ui.theme.min.css")
                ->prependStylesheet($this->basePath() . "/css/jquery-ui.theme.css")
                ->prependStylesheet($this->basePath() . "/css/jquery-ui.min.css")
                ->prependStylesheet($this->basePath() . "/css/jquery-ui.css")
                ->prependStylesheet($this->basePath() . "/css/bootstrap.css");

        echo $this->headScript()
                ->prependFile($this->basePath() . "/js/jquery-validate.js")
                ->prependFile($this->basePath() . "/js/jquery-ui.js")
                ->prependFile($this->basePath() . "/js/bootstrap.js")
                ->prependFile($this->basePath() . "/js/jquery-1.11.1.js");
        ?>
        <script>
            jQuery().ready(function() {
                jQuery('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <div class="span7">
                        <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span4">
                        <?php echo '</br>Bienvenido ' . $this->identity()->usuario_nombre . ' ' . $this->identity()->usuario_apellido; ?>
                    </div>
                    <div class="span1">
                        <?php echo "</br><a class='btn btn-warning' href=\"" . $this->basePath() . "/login/logout\">Salir</a>"; ?>
                    </div>
                </div>
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand">Salud</a>
                    <ul class="nav">
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/salud "><span class="icon-home"></span>&nbsp;Inicio</a>
                        </li>
                        <li  class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Proyectos<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->basePath(); ?>/salud/crear" title="Crear un proyecto de salud"> Crear</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="contenido" id="container">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>