<?php
$form = $this->formVerVia;
$form->prepare();
$form->setAttribute('action', $this->url . '/vias/guardar');
$form->setAttribute('method', 'post');
$form->setAttribute('ENCTYPE', 'multipart/form-data');
$form->setAttribute('class', 'form-horizontal');
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>
<div class="input-prepend span6">
    <?php
   echo'<div class="control-group">';
    $tramo = $form->get('tramo');
    echo $formLabel->openTag(array('class' => 'control-label')) . $tramo->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($tramo);
    echo'</div>';

    echo'</div><div class="control-group">';
    $dirInicio = $form->get('dirInicio');
    echo $formLabel->openTag(array('class' => 'control-label')) . $dirInicio->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($dirInicio);
    echo'</div>';

    echo'</div><div class="control-group">';
    $dirFinal = $form->get('dirFinal');
    echo $formLabel->openTag(array('class' => 'control-label')) . $dirFinal->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($dirFinal);
    echo'</div>';

    echo'</div><div class="control-group">';
    $civ = $form->get('civ');
    echo $formLabel->openTag(array('class' => 'control-label')) . $civ->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($civ);
    echo'</div>';

    echo'</div><div class="control-group">';
    $presupuesto = $form->get('presupuesto');
    echo $formLabel->openTag(array('class' => 'control-label')) . $presupuesto->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($presupuesto);
    echo'</div>';

    echo'</div><div class="control-group">';
    $largo = $form->get('largo');
    echo $formLabel->openTag(array('class' => 'control-label')) . $largo->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($largo);
    echo'</div>';

    echo'</div><div class="control-group">';
    $tipoObra = $form->get('tipoObra');
    echo $formLabel->openTag(array('class' => 'control-label')) . $tipoObra->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($tipoObra);
    echo'</div>';

    echo'</div><div class="control-group">';
    $estado = $form->get('estado');
    echo $formLabel->openTag(array('class' => 'control-label')) . $estado->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($estado);
    echo'</div>';

    echo'</div><div class="control-group">';
    $barrio = $form->get('barrio');
    echo $formLabel->openTag(array('class' => 'control-label')) . $barrio->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($barrio);
    echo'</div>';

    echo'</div><div class="control-label">';
    $coordenadas = $form->get('coordenadas');
    echo $formLabel->openTag(array('class' => 'span2')) . $coordenadas->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($coordenadas);
    echo '</div>';
    ?>
    <br>
    <ul class="gallery clearfix" width="50px">
        <?php
        foreach ($this->imagenes as $imagen) {
            echo '<li style="display: inline"><a href="' . $imagen . '" rel="imagenes[gallery1]"><img src="' . $imagen . '" style="width: 60px;height: 60px" /></a></li>';
        }
        ?>
    </ul>
</div>
<div id="googleMapSalida" class="span5" style="height: 430px"></div>
<?php
echo $this->form()->closeTag($form);
?>
<footer>
    <script type="text/javascript">
        $(document).ready(dibujarMapaSalida());
    </script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            $("area[rel^='prettyPhoto']").prettyPhoto();

            $(".gallery:first a[rel^='imagenes']").prettyPhoto({animation_speed: 'normal', theme: 'light_square', slideshow: 3000, autoplay_slideshow: false, social_tools: false});
            $(".gallery:gt(0) a[rel^='imagenes']").prettyPhoto({animation_speed: 'slow', slideshow: 10000, hideflash: true});

            $("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
                custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
                changepicturecallback: function() {
                    initialize();
                }
            });

            $("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
                custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
                changepicturecallback: function() {
                    _bsap.exec();
                }
            });
        });
    </script>
</footer>