<?php
$form = $this->formVerVia;
$form->prepare();
$form->setAttribute('action', $this->url . '/vias/guardar');
$form->setAttribute('method', 'post');
$form->setAttribute('ENCTYPE', 'multipart/form-data');
$form->setAttribute('class', 'form-horizontal');
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>
<div class="input-prepend span6">
    <?php
    echo '<div class="form-group">';
    $dirInicio = $form->get('dirInicio');
    echo $formLabel->openTag(array('class' => 'span2')) . $dirInicio->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($dirInicio);
    echo'</div><div class="form-group">';
    $dirFinal = $form->get('dirFinal');
    echo $formLabel->openTag(array('class' => 'span2')) . $dirFinal->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($dirFinal);
    echo'</div><div class="form-group">';
    $civ = $form->get('civ');
    echo $formLabel->openTag(array('class' => 'span2')) . $civ->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($civ);
    echo'</div><div class="form-group">';
    $presupuesto = $form->get('presupuesto');
    echo $formLabel->openTag(array('class' => 'span2')) . $presupuesto->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($presupuesto);
    echo'</div><div class="form-group">';
    $tipoObra = $form->get('tipoObra');
    echo $formLabel->openTag(array('class' => 'span2')) . $tipoObra->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($tipoObra);
    echo'</div><div class="form-group">';
    $estado = $form->get('estado');
    echo $formLabel->openTag(array('class' => 'span2')) . $estado->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($estado);
    echo'</div><div class="form-group">';
    $barrio = $form->get('barrio');
    echo $formLabel->openTag(array('class' => 'span2')) . $barrio->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($barrio);
    echo'</div><div class="form-group">';
    $largo = $form->get('largo');
    echo $formLabel->openTag(array('class' => 'span2')) . $largo->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($largo);
    echo'</div><div class="form-group">';
    $coordenadas = $form->get('coordenadas');
    echo $formLabel->openTag(array('class' => 'span2')) . $coordenadas->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($coordenadas);
    echo '</div>';
    ?>
    <img src="/observatorio_cb/data/49/BogotaHumana_01.png" alt=""/>
</div>
<div id="googleMapSalida" class="span5" style="height: 450px"></div>
<?php
echo $this->form()->closeTag($form);
?>
<footer>
    <script type="text/javascript">
        $(document).ready(dibujarMapaSalida());
    </script>
</footer>