<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#FormGuardarVia').validate({
            errorClass: 'text-error',
            rules: {
                tramo: {required: true, maxlength: 20},
                dirInicio: {required: true, maxlength: 20},
                dirFinal: {required: true, maxlength: 20},
                civ: {required: true, maxlength: 20},
                presupuesto: {required: true, maxlength: 20},
                tipoObra: {required: true, maxlength: 20},
                estado: {required: true, maxlength: 20},
                barrio: {required: true, maxlength: 20},
                largo: {required: true, maxlength: 20}
            },
            messages: {
                tramo: {required: 'La direccion del tramo es requerida', maxlength: 'admiten 20 caracteres'},
                dirInicio: {required: 'La direccion de inicio es requerida', maxlength: 'admiten 20 caracteres'},
                dirFinal: {required: 'La direccion final es requerida', maxlength: 'admiten 20 caracteres'},
                civ: {required: 'codigo CIV requerido', maxlength: 'admiten 20 caracteres'},
                presupuesto: {required: 'presupuesto requerido', maxlength: 'admiten 20 caracteres'},
                tipoObra: {required: 'Seleccione un tipo de obra', maxlength: 'admiten 20 caracteres'},
                estado: {required: 'Seleccione un estado', maxlength: 'admiten 20 caracteres'},
                barrio: {required: 'Seleccione un barrio', maxlength: 'admiten 20 caracteres'},
                largo: {required: 'La direccion final es requerida', maxlength: 'admiten 20 caracteres'}
            }
        });
    });
</script>
<?php
$form = $this->formCrearProyVia;
$form->prepare();
$form->setAttribute('action', $this->url . '/vias/crear');
$form->setAttribute('method', 'post');
$form->setAttribute('ENCTYPE', 'multipart/form-data');
$form->setAttribute('class', 'form-horizontal');
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>

<div class="input-prepend span6">
    <?php
    echo'<div class="control-group">';
    $tramo = $form->get('tramo');
    echo $formLabel->openTag(array('class' => 'control-label')) . $tramo->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($tramo);
    echo'</div>';

    echo'</div><div class="control-group">';
    $dirInicio = $form->get('dirInicio');
    echo $formLabel->openTag(array('class' => 'control-label')) . $dirInicio->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($dirInicio);
    echo'</div>';

    echo'</div><div class="control-group">';
    $dirFinal = $form->get('dirFinal');
    echo $formLabel->openTag(array('class' => 'control-label')) . $dirFinal->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($dirFinal);
    echo'</div>';

    echo'</div><div class="control-group">';
    $civ = $form->get('civ');
    echo $formLabel->openTag(array('class' => 'control-label')) . $civ->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($civ);
    echo'</div>';

    echo'</div><div class="control-group">';
    $presupuesto = $form->get('presupuesto');
    echo $formLabel->openTag(array('class' => 'control-label')) . $presupuesto->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($presupuesto);
    echo'</div>';

    echo'</div><div class="control-group">';
    $largo = $form->get('largo');
    echo $formLabel->openTag(array('class' => 'control-label')) . $largo->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formInput($largo);
    echo'</div>';

    echo'</div><div class="control-group">';
    $tipoObra = $form->get('tipoObra');
    echo $formLabel->openTag(array('class' => 'control-label')) . $tipoObra->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formSelect($tipoObra);
    echo'</div>';

    echo'</div><div class="control-group">';
    $estado = $form->get('estado');
    echo $formLabel->openTag(array('class' => 'control-label')) . $estado->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formSelect($estado);
    echo'</div>';

    echo'</div><div class="control-group">';
    $barrio = $form->get('barrio');
    echo $formLabel->openTag(array('class' => 'control-label')) . $barrio->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formSelect($barrio);
    echo'</div>';

    echo'</div><div class="control-group">';
    $fotos = $form->get('fotos');
    echo $formLabel->openTag(array('class' => 'control-label')) . $fotos->getOption('label') . $formLabel->closeTag();
    echo'<div class="controls">';
    echo $this->formFile($fotos);
    echo'</div>';

    echo'</div><div class="form-group">';
    $coordenadas = $form->get('coordenadas');
    echo $formLabel->openTag(array('class' => 'control-label')) . $coordenadas->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($coordenadas);
    echo '</div><div class="form-group">';
    $btnsubmit = $form->get('enviar');
    echo $this->formInput($btnsubmit);
    echo '</div><br>';
    ?>
</div>
<div id="googleMap" class="span5"  style="height: 430px;"></div>
<?php
echo $this->form()->closeTag($form);
?>

