<div>
    <script src="../../../../../public/js/mapaSencillo.js" type="text/javascript"></script>
    <script src="../../../../../public/js/drawing.js" type="text/javascript"></script>
    <script src="../../../../../public/js/mapApi.js" type="text/javascript"></script>
    <script src="../../../../../public/js/jquery-1.9.1.js" type="text/javascript"></script>
    <div style="width: 50%;float: left">
        <div id="googleMap" style="height: 400px;width: 80%;background: green; margin-left: 10%"></div>
    </div>
    <div style="width: 50%;float: left">
        <div><label style="float: left;width: 180px">Nombre de proyecto</label> <input type="text"></div>
        <div>   <label style="float: left;width: 180px">Presupuesto</label> <input type="text"></div>
        <div>   <label style="float: left;width: 180px">Objetivo</label> <textarea></textarea></div>
        <div>   <label style="float: left;width: 180px">Documento</label> <input type="file"></div>
        <div>   <label style="float: left;width: 180px">Problematica</label> <textarea></textarea></div>
        <div>   <label style="float: left;width: 180px">Dirigido a</label> <select></select></div>
        <div>   <label style="float: left;width: 180px">lugar de ejecución  upz:</label> <select></select> Barrio:<select></select></div>
        <div>   <label style="float: left;width: 180px">Direccion Inicio</label> <input type="text"></div>
        <div>   <label style="float: left;width: 180px">Direccion Final</label> <input type="text"></div>
        <div>   <label style="float: left;width: 180px">CIV </label><input type="text"></div>
        <div>   <label style="float: left;width: 180px">Largo</label> <input type="text"></div>
    </div>
</div>
