
<div class="hero-unit" style="height: 450px">
    <h1 class="cell-border">Modulo de vias </h1>
    <div class="span5">
        <img src="/Observatorio_CB/public/images/viasCB.jpg" alt="imagen Vias" style="height: 400px"/>
    </div>
    <div>
        <p>Este modulo esta creado para registrar las intervenciones realizadas en la malla vial, mejorando la movilidad y calidad de vida delos habitantes de la localidad. </p>  
    </div>
</div>
