<?php
$form = $this->formCrearProyVia;
$form->prepare();
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>
<div class="input-prepend">
    <?php
    $nombreProyecto = $form->get('nombreProyecto');
    echo $formLabel->openTag() . $nombreProyecto->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($nombreProyecto);
    $presupuesto = $form->get('presupuesto');
    echo $formLabel->openTag() . $presupuesto->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($presupuesto);
    $objetivo = $form->get('objetivo');
    echo $formLabel->openTag() . $objetivo->getOption('label') . $formLabel->closeTag();
    echo $this->formTextArea($objetivo);
    $documento = $form->get('documento');
    echo $formLabel->openTag() . $documento->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($documento);
    $problematica = $form->get('problematica');
    echo $formLabel->openTag() . $problematica->getOption('label') . $formLabel->closeTag();
    echo $this->formTextArea($problematica);
    $segmento = $form->get('segmento');
    echo $formLabel->openTag() . $segmento->getOption('label') . $formLabel->closeTag();
    echo $this->formSelect($segmento);
    $upz = $form->get('upz');
    echo $formLabel->openTag() . $upz->getOption('label') . $formLabel->closeTag();
    echo $this->formSelect($upz);
    $barrio = $form->get('barrio');
    echo $formLabel->openTag() . $barrio->getOption('label') . $formLabel->closeTag();
    echo $this->formSelect($barrio);
    $dirInicio = $form->get('dirInicio');
    echo $formLabel->openTag() . $dirInicio->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($dirInicio);
    $dirFinal = $form->get('dirFinal');
    echo $formLabel->openTag() . $dirFinal->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($dirFinal);
    $civ = $form->get('civ');
    echo $formLabel->openTag() . $civ->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($civ);
    $largo = $form->get('largo');
    echo $formLabel->openTag() . $largo->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($largo);
    $map = $form->get('map');
    
//    echo $this->formElementsErrors($nombreProyecto);
    ?>
</div>
<div id="googleMap" style="width: 500px;height: 500px">
    
</div>
<?php
echo $this->form()->closeTag($form);
?>
