<?php echo $this->permiso; ?>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script src="/js/DataTableVias.js" type="text/javascript"></script>
<script src="/js/mapApi.js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" charset="utf-8">
        loadVias();
</script>

<div class="row-fluid">
    <div class="span5">
        <h2>Edición de Proyectos</h2>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <div id="titleTable" style="width: 100%;background-color: #666;color: #FFFFFF;font: 600 larger sans-serif;height: 30px;vertical-align: middle">
        <p style="margin: 0px 18px 0px;">Lista de Usuarios</p>
    </div>
    <table class="table table-hover" id="listVias" cellpadding="10" style="width: 100%">
        <thead>
            <tr>
                <th>Año</th>
                <th>Barrio</th>
                <th>Civ</th>
                <th>Tramo</th>
                <th>Direccion Inicio</th>
                <th>Direccion Final</th>
                <th colspan="3"></th>
            </tr>
        </thead>
    </table>
</div>
<div id="dialog-edit" title="Edicion de proyecto vial">
    <?php
    $form = $this->formEditarProyVia;
    $form->prepare();
    $form->setAttribute('method', 'post');
    $form->setAttribute('ENCTYPE', 'multipart/form-data');
    $form->setAttribute('class', 'form-horizontal');
    $formLabel = $this->plugin('formLabel');
    echo $this->form()->openTag($form);
    ?>
    <div class="row-fluid"> 
        <div class="span6">
            <input type="hidden" name="Id" autofocus="autofocus">
            <?php
            echo'<div class="control-group">';
            $anio = $form->get('anio');
            echo $formLabel->openTag(array('class' => 'control-label')) . $anio->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formSelect($anio);
            echo'</div>';
            echo'</div><div class="control-group">';
            $tramo = $form->get('tramo');
            echo $formLabel->openTag(array('class' => 'control-label')) . $tramo->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($tramo);
            echo'</div>';

            echo'</div><div class="control-group">';
            $dirInicio = $form->get('dirInicio');
            echo $formLabel->openTag(array('class' => 'control-label')) . $dirInicio->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($dirInicio);
            echo'</div>';

            echo'</div><div class="control-group">';
            $dirFinal = $form->get('dirFinal');
            echo $formLabel->openTag(array('class' => 'control-label')) . $dirFinal->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($dirFinal);
            echo'</div>';

            echo'</div><div class="control-group">';
            $civ = $form->get('civ');
            echo $formLabel->openTag(array('class' => 'control-label')) . $civ->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($civ);
            echo'</div>';

            echo'</div><div class="control-group">';
            $presupuesto = $form->get('presupuesto');
            echo $formLabel->openTag(array('class' => 'control-label')) . $presupuesto->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($presupuesto);
            echo'</div>';

            echo'</div><div class="control-group">';
            $largo = $form->get('largo');
            echo $formLabel->openTag(array('class' => 'control-label')) . $largo->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($largo);
            echo'</div>';

            echo'</div><div class="control-group">';
            $ancho = $form->get('ancho');
            echo $formLabel->openTag(array('class' => 'control-label')) . $ancho->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($ancho);
            echo'</div>';

            echo'</div><div class="control-group">';
            $tipoObra = $form->get('tipoObra');
            echo $formLabel->openTag(array('class' => 'control-label')) . $tipoObra->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formSelect($tipoObra);
            echo'</div>';

            echo'</div><div class="control-group">';
            $estado = $form->get('estado');
            echo $formLabel->openTag(array('class' => 'control-label')) . $estado->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formSelect($estado);
            echo'</div>';

            echo'</div><div class="control-group">';
            $barrio = $form->get('barrio');
            echo $formLabel->openTag(array('class' => 'control-label')) . $barrio->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formSelect($barrio);
            echo'</div>';

            echo'</div><div class="control-group">';
            $ejecutor = $form->get('ejecutor');
            echo $formLabel->openTag(array('class' => 'control-label')) . $ejecutor->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formSelect($ejecutor);
            echo'</div>';

            echo'</div><div class="control-group">';
            $interventor = $form->get('interventor');
            echo $formLabel->openTag(array('class' => 'control-label')) . $interventor->getOption('label') . $formLabel->closeTag();
            echo'<div class="controls">';
            echo $this->formInput($interventor);
            echo'</div>';


            echo'</div><div class = "form-group">';
            $coordenadas = $form->get('coordenadas');
            echo $formLabel->openTag(array('class' => 'control-label')) . $coordenadas->getOption('label') . $formLabel->closeTag();
            echo $this->formInput($coordenadas);
            echo '</div>';
            echo '<br>';
            ?>
        </div>
        <div class="span5"style="padding: 2px;background-color: #204174">
            <div id="googleMapSalida" style="height: 450px;" ></div>
        </div>
        <?php
        echo $this->form()->closeTag($form);
        ?>
    </div>
    <div id="deleteDiv" title="¿Desea borrar el proyrcto vial?">
        <p><span style="float:left; margin:0 7px 20px 0;" class="icon-warning-sign"></span>&iquest;Esta seguro que desea eliminar el proyecto vial ?</p>
    </div>