
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery.jtable.es.js" type="text/javascript"></script>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script src="/js/jquery.jtable.min.js" type="text/javascript"></script>
<link href="/metro/blue/jtable.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#tablaVias').jtable({
            title: 'PROYECTOS DE VIAS',
            actions: {
                listAction: '/vias/listadoViasJson'
//          deleteAction:''
            },
            fields: {
                proyectoviasId: {key: true, create: false, list: false, edit: false},
                proyectoviasCiv: {title: 'CIV'},
                proyectoviasDirinicio: {title: 'Direccion Inicio'},
                proyectoviasDirfinal: {title: 'Direccion Final'},
                proyectoviasLargo: {title: 'Largo'}
            }
        });
        jQuery('#tablaVias').jtable('load');
    });
</script>
<div id="tablaVias">

</div>