<script>
    var trChange;
    var winModal;
    var jsonRepo;
    jQuery().ready(function() {
        creaDialog();
        galleryPrettyPhoto();
        jQuery.ajax({
            url: '/vias/cargarLista',
            type: 'POST',
            beforeSend: function(xhr) {
            },
            success: function(data, textStatus, jqXHR) {
                var tabla = jQuery('#viasRepo');
                var colorTr = '';
                jsonRepo = data.result;
                jQuery.each(data.result, function(i, item) {
                    colorTr = (item.READ == 0) ? 'warning' : '';
                    tabla.append('<tr id="' + item.ID + '" class="' + colorTr + '"><td>' + (i + 1) + '</td><td>' + item.BARRIO + '</td><td>' + item.UPZ + '</td><td>' + item.FECHA.date + '</td></tr>');
                });
                tabla.append('</tbody>');
                click();
            },
            error: function(jqXHR, textStatus, errorThrown) {
            }
        });
    });

    function creaDialog() {
        winModal = jQuery('#myModal').dialog({
            autoOpen: false,
            width: '300',
            resizable: false,
            modal: true,
            draggable: false,
            close: function() {
                if (trChange.attr('class') == 'warning') {
                    jQuery.ajax({
                        url: '<?php echo $this->basepath(); ?>/home/updateLeido',
                        type: 'POST',
                        dataType: 'JSON',
                        data: {'read': trChange.attr('id')},
                        success: function(data, textStatus, jqXHR) {
                            if (data.result == 'OK') {
                                trChange.attr('class', '');
                            } else {
                                trChange.attr('class', 'warning');
                            }
                        },
                        error: function() {
                            trChange.attr('class', 'warning');
                        }
                    });
                }
            }
        });
    }

    function click() {
        jQuery('#viasRepo > tbody > tr').click(function() {
            trChange = jQuery(this);
            jQuery.each(jsonRepo, function(j, jitem) {
                if (jitem.ID == trChange.attr('id')) {
                    var pMyModal = jQuery('#myModal p');
                    jQuery(pMyModal[0]).html(jitem.BARRIO);
                    jQuery(pMyModal[1]).html(jitem.UPZ);
                    jQuery(pMyModal[2]).html(jitem.FECHA.date);
                    jQuery(pMyModal[3]).html(jitem.DIRECC);
                    jQuery(pMyModal[4]).html(jitem.OBSV);
                    if (jitem.PHOTO != "") {
                        jQuery('#sliderPhoto').attr('class','show');
                        jQuery('#aPhoto').attr('href', '<?php echo $this->basepath(); ?>/fotografias/Reports/' + jitem.PHOTO);
                        jQuery('#imgPhoto').attr('src', '<?php echo $this->basepath(); ?>/fotografias/Reports/' + jitem.PHOTO);
                    } else {
                        jQuery('#sliderPhoto').attr('class','hidden');
                    }
                    return true;
                }
            });
            winModal.dialog('open');
        });
    }

    function galleryPrettyPhoto() {
        $("area[rel^='prettyPhoto']").prettyPhoto();

        $(".gallery:first a[rel^='imagenes']").prettyPhoto({animation_speed: 'normal', theme: 'light_square', slideshow: 3000, autoplay_slideshow: false, social_tools: false});
        $(".gallery:gt(0) a[rel^='imagenes']").prettyPhoto({animation_speed: 'slow', slideshow: 10000, hideflash: true});

        $("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
            custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
            changepicturecallback: function() {
                initialize();
            }
        });

        $("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
            custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
            changepicturecallback: function() {
                _bsap.exec();
            }
        });
    }
</script>
<div>
    <h4>Reportes reguistrados por la comunidad</h4>
</div>
<div class="row-fluid">
    <table class="table table-hover table-responsive" id="viasRepo">
        <thead>
            <tr>
                <th>#</th>
                <th>Barrio</th>
                <th>UPZ</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
    </table>
</div>
<div id="myModal" title="Detalle Reporte">
    <div class="row-fluid">
        <div class="span6">
            <label >Barrio: </label>
        </div>
        <div class="span6">
            <p  id="nombreBarrio"></p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <label class="left">UPZ: </label>
        </div>
        <div class="span6">
            <p  id="upz"></p>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <label class="left">Enviado el: </label>
        </div>
        <div class="span6">
            <p  id="fecha"></p>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <label class="left">Direccion: </label>
        </div>
        <div class="span6">
            <p  id="dir"></p>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <label class="left">Observaci&oacute;n: </label>
        </div>
        <div class="span6">
            <p  id="obs"></p>
        </div>
    </div>
    <div id="sliderPhoto" title="Fotografia" class="">
        <label>Fotografia</label>
        <ul class="gallery clearfix" width="50px">
            <li>
                <a href="" id="aPhoto" rel="imagenes[gallery1]">
                    <img src="" id="imgPhoto">
                </a>
            </li>
        </ul>
    </div>
</div>