<script>
    jQuery().ready(function() {
        jQuery.ajax({
            url: '/vias/cargarLista',
            type: 'POST',
            beforeSend: function(xhr) {
            },
            success: function(data, textStatus, jqXHR) {
                var tabla = jQuery('#viasRepo');
                var colorTr = '';
                jQuery.each(data.result, function(i, item) {
                    colorTr = (item.READ == 0) ? 'warning' : '';
                    tabla.append('<tr id="' + item.ID + '" class="' + colorTr + '"><td>' + (i + 1) + '</td><td>' + item.BARRIO + '</td><td>' + item.UPZ + '</td><td>' + item.FECHA.date + '</td></tr>');
                });
                tabla.append('</tbody>');
                eventClick();
            },
            error: function(jqXHR, textStatus, errorThrown) {
            }
        });
        
        $("#myModal").on('hidden',function(){
            alert('4444');
        });
    });
    function eventClick() {
        jQuery('#viasRepo > tbody > tr').click(function() {
            
            $("#myModal").modal('show');
        });
    }
</script>
<div>
    <h4>Reportes reguistrados por la comunidad</h4>
</div>
<div class="row-fluid">
    <table class="table table-hover table-responsive" id="viasRepo">
        <thead>
            <tr>
                <th>#</th>
                <th>Barrio</th>
                <th>UPZ</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
    </table>
</div>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Detalle Reporte</h3>
    </div>
    <div class="modal-body">
        <label>Barrio: </label><label id="nombreBarrio"></label>
        <label>UPZ: </label><label id="upz"></label>
        <label>Enviado el: </label><label id="fecha"></label>
        <label>Enviado: </label><label id="fecha"></label>
        <label>Observaci&oacute;n: </label><label id="obs"></label>
        <div id="sliderPhoto"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
    </div>
</div>