<html>
    <head>
        <meta charset="UTF-8">
        <meta content="es_ES" http-equiv="Content-Language">
        <meta content="ciudad, bolivar, observatorio, alcaldia, localidad" name="keywords">
        <title>Observatorio</title>
        <link type="text/css" rel="stylesheet" media="screen" href="/css/bootstrap.css">
        <link type="text/css" rel="stylesheet" media="screen" href="/css/jquery-ui.css">
        <link type="text/css" rel="stylesheet" media="screen" href="/css/prettyPhoto.css">
        <link type="image/vnd.microsoft.icon" rel="shortcut icon" href="/img/Bogota_escudo.png">
        <script src="/js/bootstrap.js" type="text/javascript"></script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <div class="span10">
                        <img src="/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span2">
                    </div>
                </div>
            </div>

            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand">Observatorio Social</a>
                    <ul class="nav">
                        <li>
                            <a href="#" onclick="history.go(-1);"><span class="icon-home"></span>Volver</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="contenido">
            <h1 class="text-error">Lo sentimos pero no tiene acceso esta pagina</h1>
        </div>
    </body>
</html>
