<html>
    <head>
        <meta charset="UTF-8">
        <meta content="es_ES" http-equiv="Content-Language">
        <meta content="ciudad, bolivar, observatorio, alcaldia, localidad" name="keywords">
        <title>..::Sin permiso::..</title>
        <link type="text/css" rel="stylesheet" media="screen" href="/css/bootstrap.css">
        <link type="image/vnd.microsoft.icon" rel="shortcut icon" href="/img/Bogota_escudo.png">
    </head>
    <body style="background-image: url('/img/keys.png')">
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <div class="span10">
                        <img src="/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span2">
                    </div>
                </div>
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand">Observatorio Social</a>
                    <ul class="nav">
                        <li>
                            <a href="#" onclick="history.go(-1);"><span class="icon-home"></span>Volver</a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="contenido">
            <div class="row-fluid">
                <div class="span4">
                    <img class="img-circle left" src="/img/STOP.png">
                </div>
                <div class="span8">
                    <label class="label label-important"><h1>Acceso Denegado</h1></label>
                    <h3>Lo sentimos no tiene acceso esta pagina, pongase en contacto con el administrador</h3>
                </div>
            </div>
        </div>
    </body>
</html>
