
<?php
$proyEducacion = $this->educacion;
?>

<h3 class="titulo">Detalle Proyecto Educación </h3>
 <a style="float: right" href="/educacion/listado-educacion">&laquo; Ir a Proyectos</a>
<hr>
<div class="row-fluid">
    <div class="span5" style="padding: 20px">
        <div>
            <label style="font-weight: bold" style="font-weight: bold">Vigencia : <?php echo $proyEducacion->getProyecto()->getProyectoAnio() ?></label> 
        </div>
        <div>
            <label style="font-weight: bold">Numero de proyecto : <?php echo $proyEducacion->getProyectoeducacionNumero() ?></label> 
        </div>
        <div>
            <label style="font-weight: bold">Valor Proyecto : <?php echo $proyEducacion->getProyecto()->getProyectoPresupuesto() ?></label>
        </div>
        <div >
            <label style="font-weight: bold" >Fecha Inicio : <?php echo $proyEducacion->getProyectoeducacionFechainicio()->format('d/m/Y') ?></label> 
        </div>
        <div >
            <label style="font-weight: bold" >Cupos  : <?php echo $proyEducacion->getProyectoeducacionCupos() ?></label>
        </div>
        <div >
            <label style="font-weight: bold" >Ejecutor : <?php echo $proyEducacion->getProyectoeducacionEjecutor() ?></label>
        </div>
        <div >
            <label style="font-weight: bold" >Objetivo : <?php echo $proyEducacion->getProyectoeducacionObjetivo() ?></label> 
        </div>
        <div >
            <label style="font-weight: bold" >Perfil de Beneficiario : <?php echo $proyEducacion->getProyectoeducacionPerfilbeneficiario() ?></label> 
        </div>
        <div >
            <label style="font-weight: bold" >Plazo  de Ejecución : <?php echo $proyEducacion->getProyectoeducacionPlazoejecucion() ?></label>
        </div>
    </div>
</div>
<ul class="gallery clearfix" width="50px">
    <?php
    foreach ($this->imagenes as $imagen) {
        echo '<li style="display: inline"><a href="' . $imagen . '" rel="imagenes[gallery1]"><img src="' . $imagen . '" style="width: 60px;height: 60px" /></a></li>';
    }
    ?>
</ul>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $("area[rel^='prettyPhoto']").prettyPhoto();

        $(".gallery:first a[rel^='imagenes']").prettyPhoto({animation_speed: 'normal', theme: 'light_square', slideshow: 3000, autoplay_slideshow: false, social_tools: false});
        $(".gallery:gt(0) a[rel^='imagenes']").prettyPhoto({animation_speed: 'slow', slideshow: 10000, hideflash: true});

        $("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
            custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
            changepicturecallback: function() {
                initialize();
            }
        });

        $("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
            custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
            changepicturecallback: function() {
                _bsap.exec();
            }
        });
    });
</script>
