
<?php
$datos = $this->datos;
$form = $this->formAct;
?>
<script src="/js/DataTableActividades.js" type="text/javascript"></script>
<link href="/css/jquery-ui-timepicker-addon.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
<script src="/js/datepicker-es.js" type="text/javascript"></script>
<script type="text/javascript">
    loadActividadesSalud(<?php echo $datos->id ?>);
    $(document).ready(function() {
        $('#fechaActividad').datetimepicker();
    });
</script>
<div class="row-fluid">
    <a style="float: right" href="/salud/listadosalud">&laquo; Volver a Proyectos</a>
</div>
<div class="row-fluid">
    <div class="span5">
        <h3 class="titulo">Actividades</h3>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <table class="table table-hover" id="listaActividades" cellpadding="10" style="width: 100%">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Fecha Hora</th>
                <th>Lugar </th>
                <th>Objetivos</th>
                <th colspan="3"></th>
            </tr>
        </thead>
    </table>
</div>
<div title="Actividad" id="formulario-actividades"class="row-fluid" >
    <?php
    $form->prepare();
    $form->setAttribute('class', 'form-horizontal');
    echo $this->form()->openTag($form);
    echo '<div class="span5">';
    ?>  <input style="display: none" name="Id" autofocus="autofocus">
    <input style="display: none" name="idProyecto" id="idProyecto" autofocus="autofocus"><?php
    $nombreAct = $form->get('nombreActividad');
    echo '<div class="control-group ">' . $this->formLabel($nombreAct) . '<div class="controls">' . $this->formInput($nombreAct) . '</div></div>';
    $lugarAct = $form->get('lugarActividad');
    echo '<div class="control-group ">' . $this->formLabel($lugarAct) . '<div class="controls">' . $this->formSelect($lugarAct) . '</div></div>';
    $fechaAct = $form->get('fechaActividad');
    echo '<div class="control-group ">' . $this->formLabel($fechaAct) . '<div class="controls">' . $this->formInput($fechaAct) . '</div></div>';
    echo '</div><div class="span6">';
    $objetivoAct = $form->get('objetivoActividad');
    echo '<div class="control-group">' . $this->formLabel($objetivoAct) . '<div class="controls">' . $this->formTextarea($objetivoAct) . '</div></div>';
    $requisitos = $form->get('requisitosActividad');
    echo '<div class="control-group">' . $this->formLabel($requisitos) . '<div class="controls">' . $this->formTextarea($requisitos) . '</div></div>';
    echo '</div>';
    echo $this->form()->closeTag($form);
    ?>
</div>
<div class="row-fluid">
    <input  style="float: right" id="add-activity"type="button" class="btn btn-primary" value="Nueva Actividad">
</div>
<div id="deleteDiv" title="¿Desea borrar eesta actividad?">
    <p><span style="float:left; margin:0 7px 20px 0;" class="icon-warning-sign"></span>&iquest;Seguro desea eliminar la actividad seleccionada ?</p>
</div>