<script src="/js/datepicker-es.js"></script>
<script>
    jQuery().ready(function() {
        $("#fechaIni").datepicker({
            dateFormat: 'dd-mm-yy',
            showButtonPanel: true
        });
        $("#plazoEjec").spinner({
            min: 1,
            step: 1,
            height: 15,
        });
        $("#plazoEjec").attr('style', 'border:none !important;');
    });
    /*VALIDACIONES DEL FORMULARIO*/
    jQuery(document).ready(function() {
        jQuery('#formSalud').validate({
            errorClass: 'text-error',
            rules: {
                vigencia: {required: true, maxlength: 20},
                numeroP: {required: true, maxlength: 20},
                nombreP: {required: true, maxlength: 20},
                objetivo: {required: true, maxlength: 20},
                FechaIni: {required: true, maxlength: 20},
                plazoEjec: {required: true, maxlength: 20},
                valProj: {required: true, maxlength: 20},
                segmento: {required: true, maxlength: 20},
                ejecutorP: {required: true, maxlength: 20}
            },
            messages: {
                vigencia: {required: 'Seleccione un año de vigencia'},
                numeroP: {required: 'Ingrese el numero del proyecto'},
                nombreP: {required: 'Ingrese el nombre del proyecto'},
                objetivo: {required: 'Ingrese el objetivo del proyecto'},
                FechaIni: {required: 'Eliga la fecha en la que inicia el proyecto'},
                plazoEjec: {required: 'Ingrese el numero de meses de ejecucion del proyecto'},
                valProj: {required: 'Ingrese el valos del proyecto'},
                segmento: {required: 'Seleccion el segmento de poblacion '},
                ejecutorP: {required: 'Ingrese el ejecutor del proyecto'}
            }
        });
    });
</script>
<h4 class="titulo">Crear proyecto de salud</h4>
<hr>
<div class="row-fluid">

    <?php
    $form = $this->formSalud;
    $form->prepare();
    $form->setAttribute('class', 'form-horizontal');
    echo $this->form()->openTag($form);
    echo ' <div class="span5">';
    $vigencia = $form->get('vigencia');
    echo '<div class="control-group">' . $this->formLabel($vigencia) . '<div class="controls">' . $this->formSelect($vigencia) . '</div></div>';
    $numeroP = $form->get('numeroP');
    echo '<div class="control-group">' . $this->formLabel($numeroP) . '<div class="controls">' . $this->formInput($numeroP) . '</div></div>';
    $valProj = $form->get('valProj');
    echo '<div class="control-group">' . $this->formLabel($valProj) . '<div class="input-prepend"><span class="add-on">$</span>' . $this->formInput($valProj) . '</div></div>';
    $nombreP = $form->get('nombreP');
    echo '<div class="control-group">' . $this->formLabel($nombreP) . '<div class="controls">' . $this->formInput($nombreP) . '</div></div>';
    $fechaIni = $form->get('fechaIni');
    echo '<div class="control-group">' . $this->formLabel($fechaIni) . '<div class="controls">' . $this->formInput($fechaIni) . '</div></div>';
    $segmento = $form->get('segmento');
    echo '<div class="control-group">' . $this->formLabel($segmento) . '<div class="controls">' . $this->formSelect($segmento) . '</div></div>';
    $ejecutorP = $form->get('ejecutorP');
    echo '<div class="control-group ">' . $this->formLabel($ejecutorP) . '<div class="controls">' . $this->formInput($ejecutorP) . '</div></div>';
    echo '</div><div class="span6">';
    $objetivo = $form->get('objetivo');
    echo '<div class="control-group">' . $this->formLabel($objetivo) . '<div class="controls">' . $this->formTextArea($objetivo) . '</div></div>';
    $objetoC = $form->get('objetoC');
    echo '<div class="control-group">' . $this->formLabel($objetoC) . '<div class="controls">' . $this->formTextArea($objetoC) . '</div></div>';
    $plazoEjec = $form->get('plazoEjec');
    echo '<div class="control-group">' . $this->formLabel($plazoEjec) . '<div class="controls">' . $this->formInput($plazoEjec) . '</div></div>';
    echo '</div><div class="span12">';
    $save = $form->get('almacenar');
    echo '<br><div class="control-group text-center">' . $this->formInput($save) . '</div>';
    echo '</div>';
    echo $this->form()->closeTag($form);
    ?>
</div>