<script src="/js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
<script src="/js/datepicker-es.js"></script>
<script>
    jQuery().ready(function() {
        subirFotografias();
        jQuery('#formSalud').validate({
            errorClass: 'text-error',
            rules: {
                vigencia: {required: true, maxlength: 4},
                numeroP: {required: true, maxlength: 10},
                valProj: {required: true, maxlength: 20,number:true},
                nombreP: {required: true, maxlength: 100},
                fechaIni: {required: true, maxlength: 10},
                segmento: {required: true, maxlength: 45},
                ejecutorP: {required: true, maxlength: 45},
                objetivo: {required: true, maxlength: 500},
                objetoC: {required: true, maxlength: 500},
                plazoEjec: {required: true, maxlength: 10,number:true},
                estado: {required: true, maxlength: 20}
            },
            messages: {
                vigencia: {required: 'Seleccione la vigencia del proyecto', maxlength: 'admiten 4 caracteres'},
                numeroP: {required: 'Ingrese el numero del proyecto', maxlength: 'admiten 10 caracteres',number:'el valor debe ser numerico'},
                valProj: {required: 'Ingrese el valor del proyecto', maxlength: 'admiten 20 caracteres'},
                nombreP: {required: 'Ingrese el nombre del proyecto', maxlength: 'admiten 100 caracteres'},
                fechaIni: {required: 'seleccione la fecha de inicio del proyecto', maxlength: 'admiten 10 caracteres'},
                segmento: {required: 'Seleccione el segmento de población', maxlength: 'admiten 45 caracteres'},
                ejecutorP: {required: 'Ingrese el ejecutor del proyecto', maxlength: 'admiten 500 caracteres'},
                objetivo: {required: 'Ingrese los objetivos del proyecto', maxlength: 'admiten 500 caracteres'},
                objetoC: {required: 'Ingrese el objeto contractual del proyecto', maxlength: 'admiten 10 caracteres'},
                plazoEjec: {required: 'Ingrese el plazo de ejecucion del proyecto', maxlength: 'admiten 10 caracteres',number:'El valor debe ser numerico'},
                estado: {required: 'Ingrese el estado del proyecto', maxlength: 'admiten 20 caracteres'}}

        });
        $("#fechaIni").datepicker({
            dateFormat: 'dd/mm/yy',
            showButtonPanel: true
        });
    });
</script>
<h3 class="titulo">Crear proyecto de salud</h3>
<hr>
<div class="row-fluid">
    <?php
    $form = $this->formSalud;
    $form->prepare();
    $form->setAttribute('ENCTYPE', 'multipart/form-data');
    $form->setAttribute('class', 'form-horizontal');
    echo $this->form()->openTag($form);
    echo ' <div class="span5">';
    $vigencia = $form->get('vigencia');
    echo '<div class="control-group">' . $this->formLabel($vigencia) . '<div class="controls">' . $this->formSelect($vigencia) . '</div></div>';
    $numeroP = $form->get('numeroP');
    echo '<div class="control-group">' . $this->formLabel($numeroP) . '<div class="controls">' . $this->formInput($numeroP) . '</div></div>';
    $valProj = $form->get('valProj');
    echo '<div class="control-group">' . $this->formLabel($valProj) . '<div class="controls"></span>' . $this->formInput($valProj) . '</div></div>';
    $nombreP = $form->get('nombreP');
    echo '<div class="control-group">' . $this->formLabel($nombreP) . '<div class="controls">' . $this->formInput($nombreP) . '</div></div>';
    $fechaIni = $form->get('fechaIni');
    echo '<div class="control-group">' . $this->formLabel($fechaIni) . '<div class="controls">' . $this->formInput($fechaIni) . '</div></div>';
    $segmento = $form->get('segmento');
    echo '<div class="control-group">' . $this->formLabel($segmento) . '<div class="controls">' . $this->formSelect($segmento) . '</div></div>';
    $ejecutorP = $form->get('ejecutorP');
    echo '<div class="control-group ">' . $this->formLabel($ejecutorP) . '<div class="controls">' . $this->formInput($ejecutorP) . '</div></div>';
    echo '</div><div class="span6">';
    $objetivo = $form->get('objetivo');
    echo '<div class="control-group">' . $this->formLabel($objetivo) . '<div class="controls">' . $this->formTextArea($objetivo) . '</div></div>';
    $objetoC = $form->get('objetoC');
    echo '<div class="control-group">' . $this->formLabel($objetoC) . '<div class="controls">' . $this->formTextArea($objetoC) . '</div></div>';
    $plazoEjec = $form->get('plazoEjec');
    echo '<div class="control-group">' . $this->formLabel($plazoEjec) . '<div class="controls">' . $this->formInput($plazoEjec) . '</div></div>';
    $fotos = $form->get('proyecto-fotos');
    echo '<div class="control-group">' . $this->formLabel($fotos) . '<div class="controls">' . $this->formFile($fotos) . '</div></div>';
    echo '<div id="lista-fotos"></div>';
    echo '</div><div class="span12">';
    $save = $form->get('almacenar');
    echo '<br><div class="control-group text-center">' . $this->formInput($save) . '</div>';
    echo $this->form()->closeTag($form);
    echo '</div>';
    ?>
</div>