<script src="/js/jquery-ui.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="/js/DataTableSalud.js" type="text/javascript"></script>
<script type="text/javascript">
    loadSaludPro();
</script>
<div class="row-fluid">
    <div class="span5">
        <h3 class="titulo">Edición de Proyectos</h3>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <table class="table table-hover" id="listsaludPro" cellpadding="10" style="width: 100%">
        <thead>
            <tr>
                <th>Vigencia</th>
                <th>Numero</th>
                <th>Objeto Contractual</th>
                <th>Ejecutor</th>
                <th colspan="3"></th>
            </tr>
        </thead>
    </table>
</div>
<div id="dialog-edit" title="Edicion de Proyectos">
    <div class="row-fluid">
        <?php
        $form = $this->formSalud;
        $form->prepare();
        $form->setAttribute('class', 'form-horizontal');
        echo $this->form()->openTag($form);
        echo ' <div class="span5">';
        ?>  <input type="hidden" name="Id" autofocus="autofocus"><?php
        $vigencia = $form->get('vigencia');
        echo '<div class="control-group">' . $this->formLabel($vigencia) . '<div class="controls">' . $this->formSelect($vigencia) . '</div></div>';
        $numeroP = $form->get('numeroP');
        echo '<div class="control-group">' . $this->formLabel($numeroP) . '<div class="controls">' . $this->formInput($numeroP) . '</div></div>';
        $valProj = $form->get('valProj');
        echo '<div class="control-group">' . $this->formLabel($valProj) . '<div class="controls">' . $this->formInput($valProj) . '</div></div>';
        $nombreP = $form->get('nombreP');
        echo '<div class="control-group">' . $this->formLabel($nombreP) . '<div class="controls">' . $this->formInput($nombreP) . '</div></div>';
        $fechaIni = $form->get('fechaIni');
        echo '<div class="control-group">' . $this->formLabel($fechaIni) . '<div class="controls">' . $this->formInput($fechaIni) . '</div></div>';
        $segmento = $form->get('segmento');
        echo '<div class="control-group">' . $this->formLabel($segmento) . '<div class="controls">' . $this->formSelect($segmento) . '</div></div>';
        $ejecutorP = $form->get('ejecutorP');
        echo '<div class="control-group ">' . $this->formLabel($ejecutorP) . '<div class="controls">' . $this->formInput($ejecutorP) . '</div></div>';
        echo '</div><div class="span6">';
        $objetivo = $form->get('objetivo');
        echo '<div class="control-group">' . $this->formLabel($objetivo) . '<div class="controls">' . $this->formTextArea($objetivo) . '</div></div>';
        $objetoC = $form->get('objetoC');
        echo '<div class="control-group">' . $this->formLabel($objetoC) . '<div class="controls">' . $this->formTextArea($objetoC) . '</div></div>';
        $plazoEjec = $form->get('plazoEjec');
        echo '<div class="control-group">' . $this->formLabel($plazoEjec) . '<div class="controls">' . $this->formInput($plazoEjec) . '</div></div>';
        $estado = $form->get('estado');
        echo '<div class="control-group">' . $this->formLabel($estado) . '<div class="controls">' . $this->formSelect($estado) . '</div></div>';
        echo '</div>';
        echo $this->form()->closeTag($form);
        ?>
    </div>
    <br>
    <div id="resultados" class="div-resultados" style="display:none">
        <div class="row-fluid">
            <div class="span3"> <h3 class="titulo">Resultados</h3></div>
            <div class="span4" style="margin-top: 10px">
                <span class="t1itulo">Total Participantes</span>
                <input>
            </div>
        </div>
        <div class="row-fluid">

            <div class="div-resultados span4">
                <span class="titulo">Estrato Socioeconomico</span>
                <table style="width: 100%">
                    <thead>
                        <tr><td>1</td><td>2</td><td>3</td><td>4</td></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="div-resultados span3">
                <span class="titulo">Tipo de vivienda</span>
                <table style="width: 100%">
                    <thead>
                        <tr><td>Familiar</td><td>Arriendo </td><td>Propia</td></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="div-resultados span2">
                <span class="titulo">Genero</span>
                <table>
                    <thead>
                        <tr><td>Masculino</td><td>Femenino</td></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="div-resultados span2">
                <span class="titulo">Control Vectores</span>
                <table>
                    <thead>
                        <tr><td>Hembras</td><td>Machos</td></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row-fluid">
            <div class="div-resultados span2">
                <span class="titulo">Sisben</span>
                <table>
                    <thead>
                        <tr><td>Subsidiado</td><td>Contributivo</td></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="div-resultados span5">
                <span class="titulo">Escolaridad</span>
                <table>
                    <thead>
                        <tr><td>Primaria</td><td>Basica</td><td>Bachillerato</td><td>Tecnico</td><td>Tecnologico</td><td>Profesional</td></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="div-resultados span4">
                <span class="titulo">Rango de edades</span>
                <table>
                    <thead>
                        <tr><td>niños</td><td>Adolecentes</td><td>Adultos</td><td>Adultos Mayores</td></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                            <td><input class="input-mini"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
<div id="deleteDiv" title="¿Desea borrar el proyecto?">
    <p><span style="float:left; margin:0 7px 20px 0;" class="icon-warning-sign"></span>&iquest;Esta seguro que desea eliminar el proyecto vial ?</p>
</div>
