<script src="/js/jquery-ui.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="/js/DataTableSalud.js" type="text/javascript"></script>
<script type="text/javascript">
    loadSaludPro();
</script>
<div class="row-fluid">
    <div class="span5">
        <h2>Edición de Proyectos</h2>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <div id="titleTable" style="width: 100%;background-color: #666;color: #FFFFFF;font: 600 larger sans-serif;height: 30px;vertical-align: middle">
        <p style="margin: 0px 18px 0px;">Lista de Proyecto Salud</p>
    </div>
    <table class="table table-hover" id="listsaludPro" cellpadding="10" style="width: 100%">
        <thead style="background-color: #0088cc;color: #FFFFFF">
            <tr>
                <th>Vigencia</th>
                <th>Numero</th>
                <th>Objeto Contractual</th>
                <th>Ejecutor</th>
                <th colspan="3"></th>
            </tr>
        </thead>
    </table>
</div>
<div id="dialog-edit" title="Edicion de Proyectos">
    <div class="row-fluid">
        <?php
        $form = $this->formSalud;
        $form->prepare();
        $form->setAttribute('class', 'form-horizontal');
        echo $this->form()->openTag($form);
        echo ' <div class="span5">';
        ?>  <input type="hidden" name="Id" autofocus="autofocus"><?php
        $vigencia = $form->get('vigencia');
        echo '<div class="control-group">' . $this->formLabel($vigencia) . '<div class="controls">' . $this->formSelect($vigencia) . '</div></div>';
        $numeroP = $form->get('numeroP');
        echo '<div class="control-group">' . $this->formLabel($numeroP) . '<div class="controls">' . $this->formInput($numeroP) . '</div></div>';
        $valProj = $form->get('valProj');
        echo '<div class="control-group">' . $this->formLabel($valProj) . '<div class="controls">' . $this->formInput($valProj) . '</div></div>';
        $nombreP = $form->get('nombreP');
        echo '<div class="control-group">' . $this->formLabel($nombreP) . '<div class="controls">' . $this->formInput($nombreP) . '</div></div>';
        $fechaIni = $form->get('fechaIni');
        echo '<div class="control-group">' . $this->formLabel($fechaIni) . '<div class="controls">' . $this->formInput($fechaIni) . '</div></div>';
        $segmento = $form->get('segmento');
        echo '<div class="control-group">' . $this->formLabel($segmento) . '<div class="controls">' . $this->formSelect($segmento) . '</div></div>';
        $ejecutorP = $form->get('ejecutorP');
        echo '<div class="control-group ">' . $this->formLabel($ejecutorP) . '<div class="controls">' . $this->formInput($ejecutorP) . '</div></div>';
        echo '</div><div class="span6">';
        $objetivo = $form->get('objetivo');
        echo '<div class="control-group">' . $this->formLabel($objetivo) . '<div class="controls">' . $this->formTextArea($objetivo) . '</div></div>';
        $objetoC = $form->get('objetoC');
        echo '<div class="control-group">' . $this->formLabel($objetoC) . '<div class="controls">' . $this->formTextArea($objetoC) . '</div></div>';
        $plazoEjec = $form->get('plazoEjec');
        echo '<div class="control-group">' . $this->formLabel($plazoEjec) . '<div class="controls">' . $this->formInput($plazoEjec) . '</div></div>';
        $estado = $form->get('estado');
        echo '<div class="control-group">' . $this->formLabel($estado) . '<div class="controls">' . $this->formSelect($estado) . '</div></div>';
        echo '</div>';

        echo $this->form()->closeTag($form);
        ?>
    </div>
</div>
<div id="deleteDiv" title="¿Desea borrar el proyecto?">
    <p><span style="float:left; margin:0 7px 20px 0;" class="icon-warning-sign"></span>&iquest;Esta seguro que desea eliminar el proyecto vial ?</p>
</div>
<div id="eventDiv" title="Actividades del proyecto">
    <div id="div-eventos" class="row-fluid">
      
    </div>
    <div class="row-fluid">
        <input  id="add-activity"type="button" class="btn btn-primary" value="Agregar Actividad">
    </div>
    <div id="formulario-actividades"class="row-fluid" >
        <?php
        $form2 = $this->formActividad;
        $form2->prepare();
        $form2->setAttribute('class', 'form-horizontal');
        echo $this->form()->openTag($form2);
        echo ' <div class="span5">';
        ?>  <input type="hidden" name="IdActividad" autofocus="autofocus"><?php
        $nombreAct = $form2->get('nombreActividad');
        echo '<div class="control-group ">' . $this->formLabel($nombreAct) . '<div class="controls">' . $this->formInput($nombreAct) . '</div></div>';
        $lugarAct = $form2->get('lugarActividad');
        echo '<div class="control-group ">' . $this->formLabel($lugarAct) . '<div class="controls">' . $this->formSelect($lugarAct) . '</div></div>';
        $fechaAct = $form2->get('fechaActividad');
        echo '<div class="control-group ">' . $this->formLabel($fechaAct) . '<div class="controls">' . $this->formInput($fechaAct) . '</div></div>';
        echo '</div><div class="span6">';
        $objetivoAct = $form2->get('objetivoActividad');
        echo '<div class="control-group">' . $this->formLabel($objetivoAct) . '<div class="controls">' . $this->formTextarea($objetivoAct) . '</div></div>';
        $requisitos = $form2->get('requisitosActividad');
        echo '<div class="control-group">' . $this->formLabel($requisitos) . '<div class="controls">' . $this->formTextarea($requisitos) . '</div></div>';
        echo '</div>';
        echo $this->form()->closeTag($form2);
        ?>
    </div>
</div>