<script src="/js/jquery-ui.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="/js/DataTableSalud.js" type="text/javascript"></script>
<script type="text/javascript">
    loadSaludPro();
</script>
<div class="row-fluid">
    <div class="span5">
        <h2>Edición de Proyectos</h2>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <div id="titleTable" style="width: 100%;background-color: #666;color: #FFFFFF;font: 600 larger sans-serif;height: 30px;vertical-align: middle">
        <p style="margin: 0px 18px 0px;">Lista de Proyecto Salud</p>
    </div>
    <table class="table table-hover" id="listVias" cellpadding="10" style="width: 100%">
        <thead style="background-color: #0088cc;color: #FFFFFF">
            <tr>
                <th>Vigencia</th>
                <th>Numero</th>
                <th>Objeto Contractual</th>
                <th>Ejecutor</th>
                <th colspan="3"></th>
            </tr>
        </thead>
    </table>
</div>
