<script src="/js/mapApi.js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<script src="/js/json2.js" type="text/javascript"></script>
<?php
$proySalud = $this->salud;
?>

<div class="titulo-container">
    <h3 class="titulo">Detalle Proyecto Salud </h3>
</div>
<br>
<div class="row-fluid">
    <div class="span5" style="padding: 20px">
        <div>
            <label style="font-weight: bold" style="font-weight: bold">Vigencia : <?php echo $proySalud->getProyecto()->getProyectoAnio()  ?></label> 
        </div>
        <div>
            <label style="font-weight: bold">Numero de proyecto : <?php echo $proySalud->getProyectosaludNumero() ?></label> 
        </div>
        <div>
            <label style="font-weight: bold">Valor Proyecto : <?php echo $proySalud->getProyecto()-> getProyectoPresupuesto()?></label>
        </div>
        <div >
            <label style="font-weight: bold" >Fecha Inicio : <?php echo $proySalud->getProyectosaludFechainicio()->format("d/m/Y") ?></label> 
        </div>
        <div >
            <label style="font-weight: bold" >Dirigido a  : <?php echo $proySalud->getSegmento()->getSegmentoNombre() ?></label>
        </div>
        <div >
            <label style="font-weight: bold" >Ejecutor : <?php echo $proySalud->getProyectosaludEjecutor() ?></label>
        </div>
        <div >
            <label style="font-weight: bold" >Objetivo : <?php echo $proySalud->getProyectosaludObjetivos() ?></label> 
        </div>
        <div >
            <label style="font-weight: bold" >Plazo  de Ejecución : <?php echo $proySalud->getProyectosaludPlazoejecucion() ?></label>
        </div>
    </div>
</div>
