<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta()
                ->setCharset('UTF-8')
                ->appendHttpEquiv('Content-Language', 'es_ES')
                ->appendName('keywords', 'ciudad, bolivar, observatorio, alcaldia, localidad');
        //->appendHttpEquiv('Refresh','3;URL=http://www.facebook.com/');sirve para direccionar en x cantidad de tiempo :O
        ?>
        <?php echo $this->HeadTitle($this->titulo); ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                ->prependStylesheet($this->basePath() . "/css/bootstrap-responsive.css")
                ->prependStylesheet($this->basePath() . "/css/bootstrap.css")
                ->prependStylesheet($this->basePath() . "/css/prettyPhoto.css");
        ?>     
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.js')
                ->prependFile($this->basePath() . '/js/jquery-validate.js')
                ->prependFile($this->basePath() . '/js/jquery.prettyPhoto.js')
                ->prependFile($this->basePath() . "/js/jquery-1.11.1.js")
        ?>
        <script>
            jQuery().ready(function() {
                $('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <div class="span10">
                        <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span2">
                        <?php
                        echo '</br>Bienvenido ' . $this->identity()->usuario_nombre . ' ' . $this->identity()->usuario_apellido . '</br>';
                        echo "<a class='btn btn-warning' href=\"" . $this->basePath() . "/login/logout\">Salir</a>";
                        ?>
                    </div>
                </div>
            </div>

        </header>

        <div class="container-fluid">
            <div class="row-fluid">                
                <div class="span2">
                    <ul class="nav nav-tabs nav-stacked">
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/vias"><span class="icon-home"></span>&nbsp;Inicio</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Proyectos<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->basePath(); ?>/vias/listadovias">Lista proyectos</a></li>
                                <li><a href="<?php echo $this->basePath(); ?>/vias/crear">Nuevo Proyecto</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="span10" id="container">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <!--        <footer>
                    <div class="footer">
                        <p class="text-middle">
                            Nathaly Salamanca Rativa 20081078092 &amp;  Jeisson Barrero Molina 20082078008 &COPY; 2013 - <?php echo date('Y'); ?>
                        </p>
                    </div>
                </footer>-->
    </body>
</html>
