<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta()
                ->setCharset('UTF-8')
                ->appendHttpEquiv('Content-Language', 'es_ES')
                ->appendName('keywords', 'ciudad, bolivar, observatorio, alcaldia, localidad');
        //->appendHttpEquiv('Refresh','3;URL=http://www.facebook.com/');sirve para direccionar en x cantidad de tiempo :O
        ?>
        <?php echo $this->HeadTitle($this->titulo); ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                ->prependStylesheet($this->basePath() . "/css/bootstrap-responsive.css")
                ->prependStylesheet($this->basePath() . "/css/bootstrap.css");
        ?>     
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . "/js/bootstrap.js")
                ->prependFile($this->basePath() . '/js/mapaSencillo.js')
                ->prependFile($this->basePath() . '/js/drawing.js')
                ->prependFile($this->basePath() . '/js/mapApi.js')
                ->prependFile($this->basePath() . "/js/jquery-1.11.1.js")
        ?>
        <script>
            jQuery().ready(function() {
                $('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <div class="span10">
                        <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span2">
                        <?php
                            echo '</br>Bienvenido ' . $this->identity()->usuario_nombre . ' ' . $this->identity()->usuario_apellido . '</br>';
                            echo "<a class='btn btn-warning' href=\"" . $this->basePath() . "/login/logout\">Salir</a>";                            
                        ?>
                    </div>
                </div>
            </div>
            
        </header>
        <div class="container-fluid">
            
            <?php echo $this->content; ?>
        </div>
        <footer>
            <div class="footer">
                <p class="text-middle">
                    Nathaly Salamanca Rativa 20081078092 &amp;  Jeisson Barrero Molina 20082078008 &COPY; 2013 - <?php echo date('Y'); ?>
                </p>
            </div>
        </footer>
    </body>
</html>
