<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta()
                ->setCharset('UTF-8')
                ->appendHttpEquiv('Content-Language', 'es_ES')
                ->appendName('keywords', 'ciudad, bolivar, observatorio, alcaldia, localidad');
        //->appendHttpEquiv('Refresh','3;URL=http://www.facebook.com/');sirve para direccionar en x cantidad de tiempo :O
        ?>
        <?php echo $this->HeadTitle($this->titulo); ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                //->prependStylesheet($this->basePath() . "/css/bootstrap-responsive.css")
                ->prependStylesheet($this->basePath() . "/css/jquery-ui.css")
                ->prependStylesheet($this->basePath() . "/css/bootstrap.css");
        ?>     
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . "/js/jquery-ui.js")
                ->prependFile($this->basePath() . "/js/jquery-validate.js")
                ->prependFile($this->basePath() . "/js/bootstrap.js")
                ->prependFile($this->basePath() . "/js/jquery-1.11.1.js")
        ?>
        <script>
            var dialog;
            var dialogDos;
            jQuery().ready(function() {
                jQuery('.dropdown-toggle').dropdown();
<?php if ($this->identity()) { ?>
                    jQuery('#formChangue').validate({
                        errorClass: 'text-error',
                        rules: {
                            act: {required: true},
                            newpass: {required: true},
                            reppass: {required: true, equalTo: "#newpass"},
                        },
                        messages: {
                            act: {required: 'La contraseña actual es necesaria'},
                            newpass: {required: 'Debe ingresar la nueva contraseña'},
                            reppass: {required: 'Debe ingresar de nuevo la contraseña', equalTo: 'Las contraseñas no coinciden'},
                        }
                    });
                    dialogDos = $("#dialog-message").dialog({
                        modal: true,
                        autoOpen: false,
                        buttons: {
                            'Aceptar': function() {
                                $(this).dialog("close");
                            }
                        }
                    });
                    dialog = jQuery('#divChanguePass').dialog({
                        autoOpen: false,
                        resizable: false,
                        modal: true,
                        width: 450,
                        draggable: false,
                        closeText: "Cerrar",
                        buttons: {
                            "Cambiar": function() {
                                if (jQuery('#formChangue').valid()) {
                                    $.ajax({
                                        url: "<?php echo $this->basePath(); ?>/login/change",
                                        data: JSON.parse(JSON.stringify(jQuery('#formChangue').serializeArray())),
                                        type: 'POST',
                                        dataType: 'json',
                                        success: function(data, textStatus, jqXHR) {
                                            if (data.Status === 'NOK') {
                                                dialog.dialog("close");
                                                dialogDos.dialog("open");
                                            }
                                            dialog.dialog("close");
                                        },
                                        error: function(jqXHR, textStatus, errorThrown) {
                                            dialog.dialog("close");
                                            dialogDos.dialog("open");
                                        }
                                    });
                                    dialog.dialog("close");
                                }
                            },
                            "Cancelar": function() {
                                dialog.dialog("close");
                            }
                        },
                        close: function() {
                            jQuery('#formChangue')[0].reset();
                        },
                    });
                    jQuery('#changue').click(function() {
                        dialog.dialog("open");
                    });
<?php } ?>
            });
        </script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <?php if ($this->identity()) { ?>
                        <div class="span7">
                            <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                        </div>
                        <div class="span4 text-right">
                            <?php echo '</br>Bienvenid@ ' . $this->identity()->usuario_nombre . ' ' . $this->identity()->usuario_apellido . '&nbsp; <button id="changue" title="Cambio de Contraseña" class="btn btn-mini"><i class="icon-cog"></i></button></br>'; ?>
                        </div>
                        <div class="span1"  style="margin-top: 15px;">
                            <?php echo "<a class='btn btn-warning' href=\"" . $this->basePath() . "/login/logout\">Salir</a>"; ?>
                        </div>
                    <?php } else { ?>
                        <div class="span10">
                            <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                        </div>
                        <div class="span2"  style="margin: 15px 2% 0px 0px;">
                            <a class="btn btn-info" href="<?php echo $this->basePath() ?>/login">Ingresar</a>
                        </div>
                    <?php } ?>
                </div>
            </div>

            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand">Observatorio Social</a>
                    <ul class="nav">
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/"><span class="icon-home"></span>&nbsp;Inicio</a>
                        </li>
                        <li  class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-road"></span>Vias<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->basePath(); ?>/home/reporteVia" title="Reporta una via en mal estado"> Reporta tu via</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath(); ?>/home/listadovias" title="Proyectos anteriores realizados"> Proyectos Vías</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->basePath(); ?>/home/estadisticas-vias" title="Estadisticas Generales"> Estadisticas Generales</a>
                                </li>
                            </ul>
                        </li>
                        <li  class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-plus-sign"></span>Salud<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->basePath(); ?>/home/listadosalud" title="Proyectos anteriores realizados"> Proyectos Salud</a>
                                </li>
                            </ul>
                        </li>
                        <li  class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-book"></span>Educación<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="" title="Proyectos anteriores realizados"> Proyectos Educación</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/home/lugares" title="Ver importantes lugares de la localidad"><span class="icon-globe"></span> Lugares </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/home/sugerencias" title="Buzon de sugerencias"><span class="icon-envelope"></span> Sugerencias </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath(); ?>/home/noticias" title="Noticias de actividades"><span class="icon-volume-up"></span> Noticias </a>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="contenido" id="container">
            <?php echo $this->content; ?>
        </div>
        <?php if ($this->identity()) { ?>
            <div id="divChanguePass" title="Cambiar Contraseña">
                <form class="form-horizontal" id="formChangue">
                    <div class="control-group">
                        <label class="control-label" for="act">Contrase&ntilde;a Actual: </label>
                        <div class="controls">
                            <input type="password" id="act" name="act">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Nueva Contrase&ntilde;a: </label>
                        <div class="controls">
                            <input type="password" id="newpass" name="newpass">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Confirmar Contrase&ntilde;a: </label>
                        <div class="controls">
                            <input type="password" id="reppass" name="reppass">
                        </div>
                    </div>
                </form>
            </div>
            <div id="dialog-message" title="Cambio Fallido">
                <p>
                    <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
                    En estos momentos estamos presentando inconvenientes. Por favor intente cambiar su contraseña mas tarde.
                </p>
                <p>
                    Muchas gracias, estamos trabajando para solucionar este fallo
                </p>
            </div>
        <?php } ?>
    </body>
</html>