<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php echo $this->headMeta()
                ->setCharset('UTF-8')
                ->appendHttpEquiv('Content-Language', 'es_ES')
                ->appendName('keywords','ciudad, bolivar, observatorio, alcaldia, localidad');
                //->appendHttpEquiv('Refresh','3;URL=http://www.facebook.com/');sirve para direccionar en x cantidad de tiempo :O?>
        <?php echo $this->HeadTitle($this->titulo); ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                ->prependStylesheet($this->basePath() . "/css/bootstrap-responsive.css")
                ->prependStylesheet($this->basePath() . "/css/bootstrap.css");?>     
        <?php echo $this->headScript()
                ->prependFile($this->basePath() . "/js/bootstrap.js")
                ->prependFile($this->basePath() . "/js/jquery-1.11.1.js") ?>
        <script>
            jQuery().ready(function() {
                $('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <?php
                        if($this->identity()){
                    ?>
                    <div class="span7">
                        <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span4 text-right">
                        <?php
                        echo '</br>Bienvenido ' . $this->identity()->usuario_nombre . ' ' . $this->identity()->usuario_apellido . '</br>';
                        ?>
                    </div>
                    <div class="span1"  style="margin-top: 15px;">
                        <?php echo "<a class='btn btn-warning' href=\"" . $this->basePath() . "/login/logout\">Salir</a>"; ?>
                    </div>
                        <?php }else{ ?>
                    <div class="span10">
                        <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span2"  style="margin-top: 20px;">
                        <a class="btn btn-info" href="<?php echo $this->basePath() ?>/login">Ingresar</a>
                    </div>
                        <?php } ?>
                </div>
            </div>
            
            <div class="navbar">
                    <div class="navbar-inner">
                        <a class="brand">Observatorio Social</a>
                        <ul class="nav">
                            <li>
                                <a href="<?php echo $this->basePath(); ?>/"><span class="icon-home"></span>&nbsp;Inicio</a>
                            </li>
                        </ul>
                    </div>
                </div>
        </header>
        <div class="container-fluid">
                <?php echo $this->content; ?>
        </div>
    </body>
</html>