<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
            echo $this->headMeta()
                    ->setCharset('UTF-8')
                    ->appendHttpEquiv('Content-Language', 'es_ES')
                    ->appendName('keywords', 'ciudad, bolivar, observatorio, alcaldia, localidad');
            echo $this->HeadTitle($this->titulo);
            echo $this->headLink(array('rel' => 'shortcut icon',
                        'type' => 'image/vnd.microsoft.icon',
                        'href' => $this->basePath() . '/img/Bogota_escudo.png'))
                    ->prependStylesheet($this->basePath() . "/css/bootstrap-responsive.css")
                    ->prependStylesheet($this->basePath() . "/css/bootstrap.css");

            echo $this->headScript()
                    ->prependFile($this->basePath() . "/js/bootstrap.js")
                    ->prependFile($this->basePath() . '/js/drawing.js')
                    ->prependFile($this->basePath() . "/js/jquery-1.11.1.js")
        ?>
        <script>
            jQuery().ready(function() {
                $('.dropdown-toggle').dropdown();
            });
        </script>
    </head>
    <body>
        <header>
            <div class="page-header">
                <div class="row-fluid">
                    <div class="span11">
                        <img src="<?php echo $this->basePath() ?>/img/BogotaHumana_02.png"/>
                    </div>
                    <div class="span1">
                        <a class="btn btn-info" href="<?php echo $this->basePath() ?>/application/trabajo/formulario">Ingresar</a>
                    </div>
                </div>

            </div>            
        </header>
        <div class="row">
            <div class="">
                
            </div>
        </div>
        <div class="container-fluid">
            <div class="row-fluid">                
                <div class="span2 visible-desktop">
                    <ul class="nav nav-list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Educaci&oacute;n<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Colegios</a></li>
                                <li><a href="#">Convenios</a></li>
                            </ul>

                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Salud<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Entidades</a></li>
                                <li><a href="#">Proyectos</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Vias<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Obras recientes</a></li>
                                <li><a href="#">Mapas</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="span9">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <footer>
            <div class="footer">
                <p class="text-middle">
                    Nathaly Salamanca Rativa 20081078092 &amp;  Jeisson Barrero Molina 20082078008 &COPY; 2013 - <?php echo date('Y'); ?>
                </p>
            </div>
        </footer>
    </body>
</html>