<script type="text/javascript">
    var formValid;
    jQuery().ready(function(){
        jQuery('label span').tooltip({animation:true});
        jQuery('label[for="permisos"]').attr('style','cursor:help');
        jQuery('label[for="perfil"]').attr('style','cursor:help');
        formValid=jQuery('#formAdmin').validate({
            errorClass:'text-error',
            rules:{
                nombre:{required:true,minlength:2},
                apellido:{required:true,minlength:2},
                correo:{required:true,email:true},
                perfil:{required:true}
            },
            messages:{
                nombre:{required:'Por favor ingrese un nombre valido',minlength:'Nombre demasiado corto'},
                apellido:{required:'Por favor ingrese un apellido valido',minlength:'Apellido demasiado corto'},
                correo:{required:'La direccion de correo electronico es obligatorio',email:'La direccion de correo electronico no es valido'},
                perfil:{required:'Seleccione un perfil valido'}
            }
        });
        jQuery('#correo').focusout(function(){
            var email = this.value;//.replace(/[@]/g,'\@');
            if(formValid.element(jQuery(this))){
                jQuery.ajax({
                    url:'/admin/ifExistMail',
                    data:{'email':email},
                    dataType: 'JSON',
                    type: 'POST',
                    success: function (data, textStatus, jqXHR) {
                                            if(data.existMail){
                                                jQuery('span > .controls').attr('class','');
                                                jQuery('span > .controls').attr('class','ui-icon ui-icon-circle-check');
                                                jQuery('span > .controls').attr('title','El correo es valido');
                                            }else{
                                                jQuery('span > .controls').attr('class','');
                                                jQuery('span > .controls').attr('class','ui-icon ui-icon-circle-close');
                                                jQuery('span > .controls').attr('title','El correo ya existe en la base de usuarios');
                                            }
                                        }
                });
            }
        });
    });
</script>
<div>(*) Datos Obligatorios</div>
<div class="titulo-container">
    <h3 class="titulo">Creaci&oacute;n de Usuario</h3>
    <hr>
</div>
<div class="row-fluid">
    <div class="span6">
    <?php
        $formLabel = $this->plugin('formLabel');

        $form = $this->formAdd;
        $form->prepare();
        $form->setAttribute('action',$this->url);
        $form->setAttribute('method','POST');
        $form->setAttribute('class','form-horizontal');
        $form->setAttribute('autocomplete','false');
        echo $this->form()->openTag($form); 
        $nombre = $form->get('nombre');
        echo '<div class="control-group">'.$this->formLabel($nombre).'<div class="controls">'.$this->formInput($nombre).'</div></div>';
        $apellido = $form->get('apellido');
        echo '<div class="control-group">'.$this->formLabel($apellido).'<div class="controls">'.$this->formInput($apellido).'</div></div>';
        $correo = $form->get('correo');
        echo '<div class="control-group">'.$this->formLabel($correo).'<div class="controls">'.$this->formInput($correo).''
                . '<span class=""></span></div></div>';
        $permiso = $form->get('permisos');
        echo '<i class="icon icon-bell"></i><div class="control-group">'.$this->formLabel($permiso).'<div class="controls">'.$this->formMultiCheckbox($permiso).'</div></div>';
        $perfil = $form->get('perfil');
        echo '<div class="control-group">'.$this->formLabel($perfil).'<div class="controls">'.$this->formSelect($perfil).'</div></div>';
        $submit = $form->get('crear');
        echo '<br><div class="text-center">'.$this->formInput($submit).'</div>';
        echo $this->form()->closeTag();
    ?>
    </div>
    <div class="span5 hidden-phone">
        <img src="/img/person_add.png" alt="no se encontro img">
    </div>
</div>