<script src="/js/mapApi.js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<script type="text/javascript">
    var formValid;
    jQuery().ready(function() {
        mapa_marker();
        jsonSend();
        formValid = jQuery('#formLugar').validate({
            errorClass: 'text-error',
            rules: {
                nombre: {required: true},
                direccion: {required: true},
                telefono: {required: true,number:true,minlength:7,maxlength:10 },
                tipoLugar: {required: true},
                barrio: {required: true}
            },
            messages: {
                nombre: {required: 'Por favor ingrese un nombre'},
                direccion: {required: 'Por favor ingrese un direccion'},
                telefono: {required: 'Ingrese un numero de telefono',number:'el valor debe ser numerico',minlength:'El numero es muy corto',maxlength:'El numero es muy largo'},
                tipoLugar: {required: 'Seleccione un tipo de lugar'},
                barrio: {required: 'Seleccione un barrio'}
            }
        });
    });
function jsonSend(){
    $('#formLugar').submit(function(event){
        event.preventDefault();
        if(formValid.valid()){
            $.ajax({
                url:'<?php echo $this->url; ?>',
                type: 'POST',
                data: JSON.parse(JSON.stringify($('#formLugar').serializeArray())),
                dataType: 'JSON',
                complete: function (jqXHR, textStatus ) {
                    $('#formLugar')[0].reset();
                }
            });
        }
    });
}
</script>
<div>(*) Datos Obligatorios</div>
<div class="titulo-container">
    <h3 class="titulo">Crear nuevo lugar</h3>
    <hr>
</div>
<div class="row-fluid">
    <div class="span5">
        <?php
        $formLabel = $this->plugin('formLabel');
        $form = $this->formLugar;
        $form->prepare();
        $form->setAttribute('class', 'form-horizontal');
        echo $this->form()->openTag($form);
        $nombre = $form->get('nombre');
        echo '<div class="control-group">' . $this->formLabel($nombre) . '<div class="controls">' . $this->formInput($nombre) . '</div></div>';
        $direccion = $form->get('direccion');
        echo '<div class="control-group">' . $this->formLabel($direccion) . '<div class="controls">' . $this->formInput($direccion) . '</div></div>';
        $coordenadas = $form->get('coordenadas');
        echo '<div class="controls">' . $this->formInput($coordenadas) . '</div>';
        $telefono = $form->get('telefono');
        echo '<div class="control-group">' . $this->formLabel($telefono) . '<div class="controls">' . $this->formInput($telefono) . '</div></div>';
        $tipoLugar = $form->get('tipoLugar');
        echo '<div class="control-group">' . $this->formLabel($tipoLugar) . '<div class="controls">' . $this->formSelect($tipoLugar) . '</div></div>';
        $barrio = $form->get('barrio');
        echo '<div class="control-group">' . $this->formLabel($barrio) . '<div class="controls">' . $this->formSelect($barrio) . '</div></div>';
        echo '<br><div class="text-center">';
        $btnsubmit = $form->get('enviar');
        echo $this->formInput($btnsubmit);
        echo '</div>';
        ?>
    </div>
    <div class="span5">
        <div id="map-marker" class="div_mapa" style="width: 90%;height: 300px;">

        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>
</div>