<script type="text/javascript" src="/js/DataTableLugares.js" ></script>
<script src="/js/mapApi.js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        loadLugares();
    });
</script>
<div class="row-fluid">
    <div class="span4">
        <h3 class="titulo">Edicion de Lugares</h3>
    </div>
    <div class="span4 offset4 ">
        <form class="form-search">
            <div class="input-append">
                <input type="text" title="" data-original-title="" id="txtSerch" class="span11 search-query">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid" id="contentTable">
    <div id="titleTable" style="width: 100%;background-color: #0b67cd;color: #FFFFFF;font: 600 larger sans-serif;height: 30px;vertical-align: middle" >
        &nbsp;
    </div>
    <table class="table table-hover text-center" id="listaLugares" cellpadding="10" style="width: 100%;">
        <thead style="background-color: #2D89EF;color: #FFFFFF;">
            <tr>
                <th>Nombre</th>
                <th>Direccion </th>
                <th>Telefono</th>
                <th>Barrio</th>
                <th colspan="2"></th>
            </tr>
        </thead>
    </table>
    <div class="pagination pagination-centered"></div>
</div>

<div id="dialog-edit" title="Editar Lugar">
    <div>(*) Datos Obligatorios</div>
    <div class="row-fluid">
        <div class="span5">
            <?php
            $formLabel = $this->plugin('formLabel');

            $form = $this->formLugar;
            $form->prepare();
            $form->setAttribute('action', $this->url);
            $form->setAttribute('method', 'POST');
            $form->setAttribute('class', 'form-horizontal');
            echo $this->form()->openTag($form);?>
            <input type="hidden" id="id" name="id">
            <?php
                $nombre = $form->get('nombre');
                echo '<div class="control-group">' . $this->formLabel($nombre) . '<div class="controls">' . $this->formInput($nombre) . '</div></div>';
                $direccion = $form->get('direccion');
                echo '<div class="control-group">' . $this->formLabel($direccion) . '<div class="controls">' . $this->formInput($direccion) . '</div></div>';
                $coordenadas = $form->get('coordenadas');
                echo '<div class="controls">' . $this->formInput($coordenadas) . '</div>';
                $telefono = $form->get('telefono');
                echo '<div class="control-group">' . $this->formLabel($telefono) . '<div class="controls">' . $this->formInput($telefono) . '</div></div>';
                $tipoLugar = $form->get('tipoLugar');
                echo '<div class="control-group">' . $this->formLabel($tipoLugar) . '<div class="controls">' . $this->formSelect($tipoLugar) . '</div></div>';
                $barrio = $form->get('barrio');
                echo '<div class="control-group">' . $this->formLabel($barrio) . '<div class="controls">' . $this->formSelect($barrio) . '</div></div>';
                echo '<br><div class="text-center">';
                echo '</div>';
            ?>
        </div>
        <div class="span5">
            <div id="map-marker" class="div_mapa" style="width: 90%;height: 300px;">

            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<div id="deleteDiv" title="¿Desea borrar el lugar?">
    <p><span style="float:left; margin:0 7px 20px 0;" class="icon-warning-sign"></span>&iquest;Esta seguro que desea eliminar este Lugar?</p>
</div>