<script>
    var datos;
    var winModal;
    var trClick;
    jQuery().ready(function() {
        crearDialog();
        jQuery.ajax({
            url: "/admin/listSugerencia",
            dataType: 'JSON',
            success: function(data, textStatus, jqXHR) {
                var datTable = '';
                var classW = '';
                datos = data.sug;
                jQuery.each(datos, function(i, item) {
                    classW = (item.leido) ? '' : 'warning';
                    datTable += '<tr id="' + item.id + '" class="' + classW + '"><td>' + item.nombre + ' ' + item.apellido + '</td><td>' + item.mail + '</td><td>' + item.fecha.date + '</td></tr>'
                });
                jQuery('#sugerencia tbody').append(datTable);
                clickTable();
            }
        });
    });
    function clickTable() {
        jQuery('#sugerencia > tbody > tr').click(function() {
            trClick = jQuery(this);
            var parrafo;
            $.each(datos, function(i,item){
                if(item.id == trClick.attr('id')){
                    parrafo = $('#divDetalle p');
                    jQuery(parrafo[0]).html(item.nombre);
                    jQuery(parrafo[1]).html(item.apellido);
                    jQuery(parrafo[2]).html(item.tele);
                    jQuery(parrafo[3]).html(item.mail);
                    jQuery(parrafo[4]).html(item.barrio);
                    jQuery(parrafo[5]).html(item.coment);
                }
            });
            winModal.dialog('open');
        });
    }
    function crearDialog() {
        winModal = jQuery('#divDetalle').dialog({
            autoOpen: false,
            width: '300',
            resizable: false,
            modal: true,
            draggable: false,
            close: function() {
                if (trClick.attr('class') == 'warning') {
                    jQuery.ajax({
                        url: "/admin/updateSuge",
                        dataType: 'JSON',
                        type: 'POST',
                        data: {'id': trClick.attr('id')},
                        success: function(data, textStatus, jqXHR) {
                            trClick.removeClass('warning');
                        }
                    });
                }
            }
        });

    }
</script>
<table class="table table-hover" id="sugerencia">
    <thead>
        <tr>
            <th>Nombre y Apellido</th>
            <th>Correo</th>
            <th>Fecha de Envio</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<div id="divDetalle">
    <div class="row-fluid">
        <div class="span3">
            <label>Nombre: </label>
        </div>
        <div class="span6">
            <p></p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <label>Apellido: </label>
        </div>
        <div class="span6">
            <p></p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <label>Telefono: </label>
        </div>
        <div class="span6">
            <p></p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <label>Correo: </label>
        </div>
        <div class="span6">
            <p></p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <label>Barrio: </label>
        </div>
        <div class="span6">
            <p></p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <label>Comentario: </label>
        </div>
        <div class="span6">
            <p></p>
        </div>
    </div>
</div>