<!DOCTYPE html>
<script src="/js/jquery-1.11.1.js" type="text/javascript"></script>
<link href="/css/prueba.css" rel="stylesheet" type="text/css"/>
<script src="/js/prueba.js" type="text/javascript"></script>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
<script src = "http://code.highcharts.com/maps/modules/map.js"></script>
<script src="http://code.highcharts.com/maps/modules/data.js"></script>
<script src="http://code.highcharts.com/maps/modules/exporting.js"></script>
<script src="http://code.highcharts.com/mapdata/custom/world.js"></script>
<html>
    <head>
        <meta charset="UTF-8">
        <title>estadisticas y mapas</title>
    </head>
    <body>
        <div id="container" style="max-width: 1000px; height: 50%"></div>
        <div id="chart"></div>
    </body>
</html>
