<div id="noticias" class="carousel slide">
    <ol class="carousel-indicators">
        <li data-target="#noticias" data-slide-to="0" class="active"></li>
        <li data-target="#noticias" data-slide-to="1" ></li>
        <li data-target="#noticias" data-slide-to="2" ></li>
    </ol>
    <div class="carousel-inner">
        <div class="active item" style="background-color: #BEBCD0">
            <img style="margin: 0 auto;" src="/images/noticias/colegio_ciudad_bolivar.jpg">
            <div class="carousel-caption">
                <h4>Educacion</h4>
                <p>Crear proyectos que ayuden al mejoramiento personal de cada habitante de la cominidad de Cuidad Bolivar</p>
            </div>
        </div>
        <div class="item" style="background-color: #BEBCD0">
            <img style="margin: 0 auto;" src="/images/noticias/hmeissen.jpg">
            <div class="carousel-caption">
                <h4>Salud</h4>
                <p>Ayudar en el area de la salud a la comunidad</p>
            </div>
        </div>
        <div class="item" style="background-color: #BEBCD0">
            <a href="#">
                <img style="margin: 0 auto;" src="/images/noticias/obra_vial_ciudad_bolívar.jpg">
            </a>
            <div class="carousel-caption">
                <h4>Vias</h4>
                <p>Reparar,mantener y servir al mejoramiento de la malla vial en Ciudad Bolivar</p>
            </div>
        </div>
    </div>
    <a href="#noticias" class="carousel-control left" data-slide="prev">&lsaquo;</a>
    <a href="#noticias" class="carousel-control right" data-slide="next">&rsaquo;</a>
</div>

