<h1 style="text-align: center" class="titulo">OBSERVATORIO SOCIAL DE CIUDAD BOLÍVAR</h1>
<hr>
<div id="noticias" class="carousel slide">
    <ol class="carousel-indicators">
        <li data-target="#noticias" data-slide-to="0" class="active"></li>
        <li data-target="#noticias" data-slide-to="1" ></li>
        <li data-target="#noticias" data-slide-to="2" ></li>
    </ol>
    <div class="carousel-inner">
        <div class="active item" style="background-color: #BEBCD0">
            <img style="margin: 0 auto;" src="/images/noticias/educacion.jpg">
            <div class="carousel-caption">
                <h4>Educacion</h4>
                <p>Crear proyectos que ayuden al mejoramiento personal de cada habitante de la cominidad de Cuidad Bolivar</p>
            </div>
        </div>
        <div class="item" style="background-color: #BEBCD0">
            <img style="margin: 0 auto;" src="/images/noticias/salud.jpg">
            <div class="carousel-caption">
                <h4>Salud</h4>
                <p>Ayudar en el area de la salud a la comunidad</p>
            </div>
        </div>
        <div class="item" style="background-color: #BEBCD0">
            <a href="<?php echo $this->basePath(); ?>/home/noticiasSalud">
                <img style="margin: 0 auto;" src="/images/noticias/vias.jpg">
            </a>
            <div class="carousel-caption">
                <h4>Vias</h4>
                <p>Reparar,mantener y servir al mejoramiento de la malla vial en Ciudad Bolivar</p>
            </div>
        </div>
    </div>
    <a href="#noticias" class="carousel-control left" data-slide="prev">&lsaquo;</a>
    <a href="#noticias" class="carousel-control right" data-slide="next">&rsaquo;</a>
</div>
<div class="row-fluid">
    <div class="span4">
        <h4 class="titulo">Bogotá más de 20 mil millones para ampliar cupos en universidades públicas </h4>
        <p>

            Con esta inversión, Bogotá es la primera ciudad del país que aporta de manera contundente a la ampliación y creación de nuevos cupos en 3 instituciones públicas de educación superior.
            La iniciativa permite que más de mil estudiantes egresados de colegios distritales tengan acceso a una educación superior de calidad. La convocatoria para aplicar a los nuevos cupos estará abierta del 9 al 29 de julio
        </p>
    </div>
    <div class="span4">
        <h4 class="titulo">
            <p>Implementación de estudios superiores en la localidad de Ciudad Bolívar</h4>
        En la actualidad la Secretaria de Educación del Distrito SED se encuentra adelantando el proyecto de educación  media fortalecida  y mayor acceso ala educación  superior, en el marco del cual se desarrollaran las siguientes estrategias.</p>
    </div>
    <div class="span4">
        <h4 class="titulo">Proyecto 1129 “Ciudad Bolívar Construye Saberes” Vigencia 2014</h4>
        <p>Meta PDL: “Vincular 500 personas como mínimo con programas de preparación y capacitación para primaria o bachillerato dirigido a jóvenes y adultos en edad extraescolar.”

            En el período 2007-2011 la tasa de analfabetismo en Bogotá disminuyó de 1,8% a 1,6%, alcanzando el 1,3% en hombres de 15 y más años, y el 1,9% en mujeres. Esta tasa significa que en Bogotá cerca de 91.793 personas de 15 y más años, no saben leer ni escribir, de los cuales 34.119 son  hombres y 57.674 son mujeres.</p>
    </div>
</div>
<h2 class="titulo">¿Que es el observatorio ?</h2>
<hr>

<p style="font-size:16px;"> El observatorio social de Ciudad Bolivar es un sistema  que provee información de la gestión local, permite hacer seguimiento a las inversiones que se ejecutan el en marco del plan de desarrollo local 
mediante estadisticas, indicadores georeferenciados y fotografias</p>