<h1>CONTENIDO modificado por Nata</h1>
<script>
 series: [{
            name: '<?php echo 'tokio'; ?>',
            data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
        },
</script>
<?php
/*foreach ($this->resultado as $value) {
    echo '<p>nombre='.$value['nombre_usuario'].'</p>'.'<p>contrase&ntilde;a='.$value['password_ususario'].'</p>';
}*/
var_dump($this->resultado);

