<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script src="/js/DataTableVias.js" type="text/javascript"></script>
<script src="/js/mapApi.js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<link href="/css/prettyPhoto.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery.prettyPhoto.js" type="text/javascript"></script>
<script type="text/javascript" charset="utf-8">
    loadViasPublic();
</script>

<div class="row-fluid">
    <div class="span5">
        <h3 class="titulo">Proyectos viales</h3>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <table class="table table-hover" id="listVias" cellpadding="10" style="width: 100%">
        <thead>
            <tr>
                <th>Año</th>
                <th>Barrio</th>
                <th>Civ</th>
                <th>Tramo</th>
                <th>Direccion Inicio</th>
                <th>Direccion Final</th>
                <th colspan="3"></th>
            </tr>
        </thead>
    </table>
</div>

<div id="dialog-ver" title="Detalle proyecto">
    <br>
    <div class="row-fluid">
        <div class="span5" style="padding: 20px">
            <div>
                <span><b>Año: </b><span id="anio"></span></span> 
            </div>
            <div>
                <span><b>Civ: </b><span id="civ"></span></span> 
            </div>
            <div>
                <span><b>Tramo: </b><span id="tramo"></span></span> 
            </div>
            <div>
                <span><b>Dirección Inicial: </b><span id="dirInicio"></span></span> 
            </div>
            <div>
                <span><b>Dirección Final : </b><span id="dirFinal"></span></span> 
            </div>
            <div>
                <span><b>Presupuesto : </b><span id="presupuesto"></span> Millones</span> 
            </div>
            <div>
                <span><b>Ancho : </b><span id="ancho"></span> mts </span> 
                <span><b>Largo : </b><span id="largo"></span> mts </span> 
            </div>
            <div>
                <span><b>Estado: </b><span id="estado"></span></span> 
            </div>
            <div>
                <span><b>Tipo de Obra: </b><span id="tipoObra"></span></span> 
            </div>
            <div>
                <span><b>Barrio: </b><span id="barrio"></span></span> 
            </div>
            <div>
                <span><b>Upz: </b><span id="upz"></span></span> 
            </div>
            <div>
                <span><b>Ejecutor: </b><span id="ejecutor"></span></span> 
            </div>
            <div>
                <span><b>Interventor: </b><span id="interventor"></span></span> 
            </div>
            <div>
                <input id="coordenadas" type="hidden" value="">
            </div>
            <br>
            <ul id="gallery" class="gallery clearfix" width="50px">
            </ul>
        </div>
        <div class="span5"style="padding: 2px;background-color: #204174">
            <div id="googleMapSalida"  style="height: 430px"></div>
        </div>
    </div>
</div>