<script src="/js/jquery-ui.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="/js/DataTableEducacion.js" type="text/javascript"></script>
<script type="text/javascript">
    loadEducacionPublic();
</script>
<div class="row-fluid">
    <div class="span5">
        <h3 class="titulo">Proyectos Educación</h3>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <table class="table table-hover" id="listEducacionPro" cellpadding="4" style="width: 100%">
        <thead>
            <tr>
                <th>Vigencia</th>
                <th>Numero</th>
                <th>Nombre</th>
                <th>Cupos</th>
                <th>Objetivo</th>
                <th>Ejecutor</th>
                <th colspan="1"></th>
            </tr>
        </thead>
    </table>
</div>

