<script src="/js/jquery-ui.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="/js/DataTableSalud.js" type="text/javascript"></script>
<script type="text/javascript">
    loadSaludPublic();
</script>
<div class="row-fluid">
    <div class="span5">
        <h3 class="titulo">Edición de Proyectos</h3>
    </div>
    <div class="span4 offset2 ">
        <form class="form-search">
            <div class="input-append" style="margin-top: 15px">
                <input id="txtSerch" class="span11 search-query" type="text" data-original-title="" title="">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <table class="table table-hover" id="listsaludPro" cellpadding="4" style="width: 100%">
        <thead>
            <tr>
                <th>Vigencia</th>
                <th>Numero</th>
                <th>Objeto Contractual</th>
                <th>Ejecutor</th>
                <th colspan="1"></th>
            </tr>
        </thead>
    </table>
</div>

<div id="dialog-ver" title="Detalle proyecto">
    <br>
    <div class="row-fluid">
        <div class="span5" style="padding: 20px">
            <div>
                <span><b>Vigencia: </b><span id="vigencia"></span></span> 
            </div>
            <div>
                <span><b>Numero de Proyecto: </b><span id="numero"></span></span> 
            </div>
            <div>
                <span><b>Valor de proyecto: </b><span id="valor"></span></span> 
            </div>
            <div>
                <span><b>Nombre de Proyecto: </b><span id="nombre"></span></span> 
            </div>
            <div>
                <span><b>fecha de Inicio : </b><span id="fechaInicio"></span></span> 
            </div>
            </div><div class="span6">
            <div>
                <span><b>Dirigido a : </b><span id="segmento"></span></span>
            </div>
            <div>
                <span><b>Ejecutor: </b><span id="ejecutor"></span></span> 
            </div>
            <div>
                <span><b>Objetvos: </b><span id="objetivos"></span></span> 
            </div>
            <div>
                <span><b>Objeto Contractual: </b><span id="objeto"></span></span> 
            </div>
            <div>
                <span><b>Plazo de Ejecucion: </b><span id="plazo"></span></span> 
            </div>
            <div>
                <span><b>Estado: </b><span id="estado"></span></span> 
            </div>
        </div>