<script src="https://maps.googleapis.com/maps/api/js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        $.ajax({
            url: '/home/jsonlugares',
            type: 'POST',
            beforeSend: function(xhr) {
            },
            success: function(data, textStatus, jqXHR) {
                mapa_lugares(data);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                alert('error');
            }
        });
    });
</script>
<div class="titulo-container">
    <h3 class="titulo">Conoce los lugares de tu localidad</h3>
    <hr>
</div>
<div id="mapa_lugares" style="width: 100%;height: 400px; border-radius: 25px;
     border: 1px solid #002a80;">
</div>