<script src="/js/mapApi.js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        $.ajax({
            url: '/home/jsonlugares',
            type: 'POST',
            beforeSend: function(xhr) {
            },
            success: function(data, textStatus, jqXHR) {
              mapa_lugares(data);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                alert('error');
            }
        });
    });
</script>
<div id="mapa_lugares" style="width: 90%;height: 500px;background-color: #002a80">

</div>