<script src="/js/jquery-ui.js" type="text/javascript"></script>
<link href="/css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="/js/mapApi.js" type="text/javascript"></script>
<script src="/js/mapaSencillo.js" type="text/javascript"></script>
<script src="/js/json2.js" type="text/javascript"></script>
<script type="text/javascript"></script>
<?php $actividades = $this->listado;
?>
<h3 class="titulo">Noticias</h3>
<hr>
<?php
foreach ($actividades as $act) {
    echo'<div class="div-actividad" >
    <div class="row-fluid">
        <div class="row-fluid"><h4 class="titulo">' . $act->getActividadNombre() . '</h4></div>
    <div class="span5">
        <span class="lblng">Lugar : </span><span>' . $act->getLugar()->getLugarNombre() . '</span>
            <a style="cursor:pointer" name="ver-mapa">ver mapa <span style="Display:none;" >' . $act->getLugar()->getLugarCoordenadas() . '</span>
<div style="display: none">
    <h4 class="titulo">' . $act->getLugar()->getLugarNombre() . '</h4>
    <span class="lblng">Barrio: </span><span>' . $act->getLugar()->getBarrio()->getBarrioNombre() . '</span><br>
    <span class="lblng">UPZ: </span><span>' . $act->getLugar()->getBarrio()->getUpz()->getUpzNombre() . '</span><br>
    <span class="lblng">Direccion: </span><span>' . $act->getLugar()->getLugarDireccion() . '</span><br>
    <span class="lblng">Telefono: </span><span>' . $act->getLugar()->getLugarTelefono() . '</span><br>
</div>                
</a><br> 
        <span class="lblng">Fecha y Hora : </span><span>' . $act->getActividadFechahora()->format('d/m/Y H:i') . '</span><br>
        <span class="lblng">Objetivos : </span><span>' . $act->getActividadObjetivo() . '</span<br>
    </div>
   <div class="span5">
        <span class="lblng">Requisitos : </span><span>' . $act->getActividadRequisitos() . '</span>
    </div>
    </div>
</div>';
}
?>
</div>
<div id="mapa-lugar" title="Lugar de Actividad">
    <div id="ubicacion" style="width: 100%;height: 250px;">

    </div>
    <div id="detalle-lugar" style="padding: 5px;"> 
    </div>
</div>

<script type="text/javascript">
    $('a[name="ver-mapa"').click(function() {
        var text = $(this).find('span').html();
        var detalle = $(this).find('div').html();
        $('#detalle-lugar').html(detalle);
        //s mapaAceetividad(teext);
        dialogVerMapa.dialog('open');
        mapaActividad(text);
    });

    dialogVerMapa = $('#mapa-lugar').dialog({
        autoOpen: false,
        width: 500,
        resizable: false,
        modal: true,
        draggable: false,
        buttons: {
            Cerrar: function() {
                $('#ubicacion').html("");
                dialogVerMapa.dialog("close");
            }
        },
        close: function() {
        }
    });
</script>
