
<div class="titulo-container">
    <h3 class="titulo">Reportanos una via en mal estado</h3>
</div>
<p>Con tu ayuda podemos mejorar la calidad de las vias en nuestra localidad, informanos de una via que necesite intervecion</p>
<?php
$form = $this->formReporte;
$form->prepare();
echo $this->form()->openTag($form);
$tipoCalle = $form->get('tipoCalle');
echo $this->formLabel($tipoCalle) . $this->formSelect($tipoCalle);
$fNum = $form->get('firsthNum');
echo $this->formInput($fNum);
$fLetter = $form->get('letraFirNum');
echo $this->formSelect($fLetter);
$bis = $form->get('bis');
echo ' Bis ' . $this->formCheckbox($bis) . ' # ';
$secondNum = $form->get('secondNum');
echo $this->formInput($secondNum);
$letraSecNum = $form->get('letraSecNum');
echo $this->formSelect($letraSecNum) . ' - ';
$lastNum = $form->get('lastNum');
echo $this->formInput($lastNum);
$txtarea= $form->get('observacion');
echo $this->formLabel($txtarea) . $this->formTextArea($txtarea);
$barrios = $form->get('barrios');
echo $this->formLabel($barrios) . $this->formSelect($barrios);
?>
    <label>Adjuntar Foto:</label>
    <input type="file" accept="image/x-png,image/jpeg"><br>
    <input type="submit" value="Reportar" class="btn btn-primary">
<?php
echo $this->form()->closeTag();
?>
