<div class="">
    <form class="form-horizontal">
        <div class="row">
            <div class="span4">
                <label class="label label-info">Nombre: </label>
            </div>
            <div class="span4">
                <label class="label label-info">Apellido: </label>
            </div>
        </div>
        <div class="row">
            <div class="span4">
                <input type="text" id="nombre" class="span4">
            </div>
            <div class="span4">
                <input type="text" id="asunto">
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <label class="label label-info">Telefono: </label>
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <input type="text" id="telefono" class="span7">
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <label class="label label-info">Correo: </label>
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <input type="text" id="mail" class="span7">
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <label class="label label-info">Barrio: </label>
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <select class="span7">
                    <option value="1">Candelaria</option>
                    <option value="2">San Francisco</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <label class="label label-info">Comentarios y sugerencias: </label>
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <textarea id="desc" placeholder="Ingresa la descripcion de tu sugerencia..." class="span7" rows="6"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <input type="submit" class="btn btn-info">
            </div>
        </div>
    </form>
</div>