<script>
    jQuery().ready(function() {
        jQuery('form').validate({
            errorClass: 'text-error',
            rules: {
                barrios: {required: true},
                observacion: {required: true, minlength: 10},
                nombre: {required: true, minlength: 3},
                apellido: {required: true, minlength: 4},
                tele: {required: true, minlength: 7, maxlength: 10},
                mail: {required: true, email: true}
            },
            messages: {
                barrios: {required: 'Debe seleccionar un barrio'},
                observacion: {required: 'Debe ingresar una observacion', minlength: 'La observacion debe ser de minimo {0} caracteres'},
                nombre: {required: 'Debe ingresar un nombre', minlength: 'El nombre no puede ser menor a {0} caracters'},
                apellido: {required: 'Debe ingresar un apellido', minlength: 'El apellido debe ser mayor a {0} caracteres'},
                tele: {required: 'Debe ingresar un numero de telefono', minlength: 'El numero telefonico no es valido', maxlength: 'El numero telefonico es demasiado largo'},
                mail: {required: 'Debe ingresar un correo', email: 'El correo electronico no es valido'}
            }
        });
        $('form').submit(function(event) {
            event.preventDefault();
            if (jQuery(this).valid()) {
                jQuery.ajax({
                    url: '/home/saveSugerencia',
                    method: 'POST',
                    data: JSON.parse(JSON.stringify($(this).serializeArray())),
                    success: function(data, textStatus, jqXHR) {
                        alert(textStatus);
                    },
                    beforeSend: function(xhr) {
                        console.log(xhr);
                    }
                });
            }
        });
    });
</script>
<div>
    <?php
    $form = $this->formSugerencia;
    $form->prepare();
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $selecBarrio = $form->get('barrios');
    $obs = $form->get('observacion');
    $nombre = $form->get('nombre');
    $apellido = $form->get('apellido');
    $tele = $form->get('tele');
    $mail = $form->get('mail');
    ?>
    <div class="row">
        <div class="span4">
            <label >Nombre: </label>
        </div>
        <div class="span4">
            <label >Apellido: </label>
        </div>
    </div>
    <div class="row">
        <div class="span4">
            <?php echo $this->formInput($nombre); ?>
        </div>
        <div class="span4">
            <?php echo $this->formInput($apellido); ?>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <label >Telefono: </label>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <?php echo $this->formInput($tele); ?>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <label >Correo: </label>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <?php echo $this->formInput($mail); ?>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <label >Barrio: </label>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <?php echo $this->formSelect($selecBarrio); ?>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <label >Comentarios y sugerencias: </label>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <?php echo $this->formTextArea($obs); ?>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <input type="submit" class="btn btn-info" value="Enviar Sugerencia">
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>