<script type="text/javascript">
    jQuery().ready(function(){
        jQuery('#formAdmin').validate({
            errorClass:'text-error',
            rules:{
                nombre:{required:true,minlength:2},
                apellido:{required:true,minlength:2},
                correo:{required:true,email:true},
                perfil:{required:true}
            },
            messages:{
                nombre:{required:'Por favor ingrese un nombre valido',minlength:'Nombre demasiado corto'},
                apellido:{required:'Por favor ingrese un apellido valido',minlength:'Apellido demasiado corto'},
                correo:{required:'La direccion de correo electronico es obligatorio',email:'La direccion de correo electronico no es valido'},
                perfil:{required:'Seleccione un perfil valido'}
            }
        });
    });
</script>
<div class="row-fluid">
    <h2>Creaci&oacute;n de Usuario</h2>
</div>
<div class="row-fluid">
    <div class="span6">
    <?php
        $formLabel = $this->plugin('formLabel');

        $form = $this->formAdd;
        $form->prepare();
        $form->setAttribute('action',$this->url);
        $form->setAttribute('method','POST');
        $form->setAttribute('class','form-horizontal');
        echo $this->form()->openTag($form); 
        $nombre = $form->get('nombre');
        echo '<div class="control-group">'.$this->formLabel($nombre).'<div class="controls">'.$this->formInput($nombre).'</div></div>';
        $apellido = $form->get('apellido');
        echo '<div class="control-group">'.$this->formLabel($apellido).'<div class="controls">'.$this->formInput($apellido).'</div></div>';
        $correo = $form->get('correo');
        echo '<div class="control-group">'.$this->formLabel($correo).'<div class="controls">'.$this->formInput($correo).'</div></div>';
        $permiso = $form->get('permisos');
        echo '<div class="control-group">'.$this->formLabel($permiso).'<div class="controls">'.$this->formMultiCheckbox($permiso).'</div></div>';
        $perfil = $form->get('perfil');
        echo '<div class="control-group">'.$this->formLabel($perfil).'<div class="controls">'.$this->formSelect($perfil).'</div>';
        $submit = $form->get('crear');
        echo '<br>'.$this->formInput($submit).'</div>';
        echo $this->form()->closeTag();
    ?>
    </div>
    <div class="span5 hidden-phone">
        <img src="/img/person_add.png" alt="no se encontro img">
    </div>
</div>