<script type="text/javascript">
    jQuery().ready(function(){
        jQuery('#formAdmin').validate({
            errorClass:'text-error',
            rules:{
                nombre:{required:true,minlength:2},
                apellido:{required:true,minlength:2},
                correo:{required:true,email:true},
                perfil:{required:true}
            },
            messages:{
                nombre:{required:'Por favor ingrese un nombre valido',minlength:'Nombre demasiado corto'},
                apellido:{required:'Por favor ingrese un apellido valido',minlength:'Apellido demasiado corto'},
                correo:{required:'La direccion de correo electronico es obligatorio',email:'La direccion de correo electronico no es valido'},
                perfil:{required:'Seleccione un perfil valido'}
            }
        });
    });
</script>
<h2>Creaci&oacute;n de Usuario</h2>
<div class="row-fluid">
    <div class="span5">
    <?php
        $formLabel = $this->plugin('formLabel');

        $form = $this->formAdd;
        $form->prepare();
        $form->setAttribute('action',$this->url);
        $form->setAttribute('method','POST');

        echo $this->form()->openTag($form); 
        $nombre = $form->get('nombre');
        echo $formLabel->openTag(). $nombre->getOption('label').$formLabel->closeTag().$this->formInput($nombre);
        $apellido = $form->get('apellido');
        echo $formLabel->openTag(). $apellido->getOption('label').$formLabel->closeTag().$this->formInput($apellido);
        $correo = $form->get('correo');
        echo $formLabel->openTag(). $correo->getOption('label').$formLabel->closeTag().$this->formInput($correo);

        $perfil = $form->get('perfil');
        echo $formLabel->openTag(). $perfil->getOption('label').$formLabel->closeTag().$this->formSelect($perfil);

        $submit = $form->get('crear');
        echo '<br>'.$this->formInput($submit);

    ?>
    </div>
    <div class="span5">
        <img src="/img/person_add.png" alt="no se encontro img">
    </div>
</div>