<script type="text/javascript" src="/js/DataTable.js" ></script>
    <h2>Edicion de Usuarios</h2>
    <div id="titleTable" style="width: 100%;background-color: #0b67cd;color: #FFFFFF;font: 600 larger sans-serif;height: 30px;vertical-align: middle" >
        &nbsp;
    </div>
    <table class="table table-hover" id="listUser" cellpadding="10" style="width: 100%">
        <thead style="background-color: #2D89EF;color: #FFFFFF">
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Correo</th>
                <th>Perfil</th>
                <th>Permisos</th>
                <th colspan="2"></th>
            </tr>
        </thead>
    </table>
    <div id="dialog-edit" title="Editar Usuario">
        <form id="form-dialog" class="form-horizontal">
            <input type="hidden" name="Id">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="nombre">
            </div>
            <div class="form-group">
                <label>Apellido</label>
                <input type="text" name="apellido">
            </div>
            <div class="form-group">
                <label>Correo</label>
                <input type="text" name="correo">
            </div>
            <div class="form-group">
                <label>Perfil</label>
                <select id="profiles" name="perfil">
                    <option value="">--Seleccione Perfil--</option>
                </select>
            </div>
            <hr>
            <label>Permisos</label>
        </form>
    </div>
    <div id="deleteDiv" title="¿Desea borrar el usuario?">
        <p><span style="float:left; margin:0 7px 20px 0;" class="icon-warning-sign"></span>&iquest;Esta seguro que desea eliminar al usuario?</p>
    </div>