<script type="text/javascript" src="/js/DataTableUsuarios.js" ></script>
<script type="text/javascript" src="/js/PaginatorTables.js"></script>
<div class="row-fluid">
    <div class="span4">
        <h2>Edici&oacute;n de Usuarios</h2>
    </div>
    <div class="span4 offset4 ">
        <form class="form-search">
            <div class="input-append">
                <input type="text" title="" data-original-title="" id="txtSerch" class="span11 search-query">
                <button id="serch" class="btn" type="button">Buscar</button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid" id="contentTable">
    <div id="titleTable" style="width: 100%;background-color: #0b67cd;color: #FFFFFF;font: 600 larger sans-serif;height: 30px;vertical-align: middle" >
        &nbsp;
    </div>
    <table class="table table-hover text-center" id="listUser" cellpadding="10" style="width: 100%;">
        <thead style="background-color: #2D89EF;color: #FFFFFF;">
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Correo</th>
                <th>Perfil</th>
                <th>Permisos</th>
                <th colspan="2"></th>
            </tr>
        </thead>
    </table>
    <div class="pagination pagination-centered"></div>
</div>

<div id="dialog-edit" title="Editar Usuario">
    <?php
    $formLabel = $this->plugin('formLabel');
    $form = $this->formEdit;
    $form->prepare();
    $form->setAttribute('class', 'form-horizontal');
    echo $this->form()->openTag($form);
    ?>
    <input type="hidden" name="Id" autofocus="autofocus">
    <?php
    $nombre = $form->get('nombre');
    echo '<div class="control-group">' . $this->formLabel($nombre) . '<div class="controls">' . $this->formInput($nombre) . '</div></div>';
    $apellido = $form->get('apellido');
    echo '<div class="control-group">' . $this->formLabel($apellido) . '<div class="controls">' . $this->formInput($apellido) . '</div></div>';
    $correo = $form->get('correo');
    echo '<div class="control-group">' . $this->formLabel($correo) . '<div class="controls">' . $this->formInput($correo) . '</div></div>';
    $perfil = $form->get('perfil');
    echo '<div class="control-group">' . $this->formLabel($perfil) . '<div class="controls">' . $this->formSelect($perfil) . '</div></div>';
    $permiso = $form->get('permisos');
    echo '<div class="control-group">' . $this->formLabel($permiso) . '<div class="controls">' . $this->formMultiCheckbox($permiso) . '</div></div>';
    ?>
</div>
<div id="deleteDiv" title="¿Desea borrar el usuario?">
    <p><span style="float:left; margin:0 7px 20px 0;" class="icon-warning-sign"></span>&iquest;Esta seguro que desea eliminar al usuario?</p>
</div>